"""Registro único de modelos y secuencias para Alembic y el arranque."""

from app.database.sequences import (
    research_participant_code_sequence,
    shipment_tracking_sequence,
)
from app.models.branch import Branch
from app.modules.logistics.rbac.models_role import LogisticsRole
from app.modules.logistics.rbac.models_scope_rule import LogisticsRoleScopeRule
from app.modules.logistics.rbac.models_assignment import LogisticsRoleAssignment
from app.modules.logistics.rbac.models_conflict import LogisticsRoleConflictRule
from app.modules.logistics.rbac.models_permission import LogisticsPermission
from app.modules.logistics.rbac.models_role_permission import LogisticsRolePermission
from app.modules.logistics.rbac.models_permission_scope import LogisticsPermissionScopeRule
from app.modules.logistics.audit.models_event import LogisticsAuditEvent
from app.modules.logistics.security.models_stepup import StepUpChallenge, StepUpProof
from app.models.audit_log import AuditLog
from app.models.behavioral_batch import BehavioralBatch
from app.models.client import Client
from app.models.consent_record import ConsentRecord
from app.models.continuous_auth_evaluation import ContinuousAuthEvaluation
from app.models.device import Device
from app.models.entity_code_counter import EntityCodeCounter
from app.models.experimental_session import ExperimentalSession
from app.models.facial_capture import FacialCapture
from app.models.incident import Incident
from app.models.inventory_item import InventoryItem
# NOTE: The legacy ``app.models.inventory_movement.InventoryMovement`` model is
# superseded by the Phase 044 append-only ``InventoryMovementModel`` living
# under ``app.modules.logistics.inventory.ledger``. The legacy ORM row is kept
# for backwards compatibility of imports, but it is no longer registered in
# the global SQLAlchemy ``Base.metadata`` to avoid table name collisions and
# because the new model is the only one that must be created by Alembic.
import app.models.inventory_movement  # noqa: F401  -- legacy import retained
from app.models.logistics_route import LogisticsRoute
from app.models.research_participant import ResearchParticipant
from app.models.risk_event import RiskEvent
from app.models.route_shipment import RouteShipment
from app.models.organization import Organization
from app.models.session import UserSession
from app.models.shipment import Shipment
from app.models.shipment_event import ShipmentEvent
from app.models.user import User
from app.models.warehouse import Warehouse
from app.modules.logistics.geography import models as _geography_models  # noqa: F401
from app.modules.logistics.warehouses import models as _warehouse_location_models  # noqa: F401

# Import putaway models (Phase 043)
from app.modules.logistics.inventory.putaway.infrastructure.persistence.models import (
    PutawayPolicyModel,
    PutawayPolicyVersionModel,
    StorageCompatibilityRuleModel,
    WarehouseLocationCapacityProfileModel,
    PutawayLocationCapacityProjectionModel,
    WarehouseLocationProximityProfileModel,
    PutawayRecommendationRunModel,
    PutawayLocationCandidateModel,
    PutawayOrderModel,
    PutawayOrderRevisionModel,
    PutawayTaskModel,
    PutawayTaskDestinationModel,
    PutawayTaskAssignmentModel,
    PutawayLocationReservationModel,
    PutawayExecutionSessionModel,
    PutawayScanEventModel,
    PutawayPlacementConfirmationModel,
    PutawayLocationOverrideModel,
    PutawayTaskExceptionModel,
    PutawayTaskPauseModel,
    OperationalInventoryPlacementModel,
    PutawayLocationPlacementProjectionModel,
)

# Phase 044 — Inventory ledger (append-only book)
from app.modules.logistics.inventory.ledger.infrastructure.persistence.models import (
    InventoryLedgerPartitionModel,
    InventoryPositionModel,
    InventoryExternalBoundaryModel,
    InventoryMovementPostingRequestModel,
    InventoryMovementModel,
    InventoryMovementLineModel,
    InventoryMovementSourceReferenceModel,
    InventoryMovementCompensationRequestModel,
    InventoryLedgerCheckpointModel,
    InventoryLedgerReconciliationJobModel,
    InventoryLedgerReconciliationResultModel,
    InventoryKardexExportJobModel,
    InventoryLedgerOutboxEventModel,
)

# Import logistics document models
from app.modules.logistics.documents.models import (
    DocumentFamilyModel,
    DocumentRetentionPolicyModel,
    DocumentTypeModel,
    DocumentTypeVersionModel,
    DocumentCatalogVersionModel,
    DocumentInstanceModel,
    DocumentSnapshotModel,
    DocumentArtifactModel,
    DocumentReprintModel,
    DocumentCancellationModel,
    DocumentExportJobModel,
)
from app.modules.logistics.documents.rendering.template_models import (
    DocumentTemplateModel,
    DocumentTemplateVersionModel,
    DocumentTemplateAssetModel,
)
from app.modules.logistics.documents.codes.code_models import (
    DocumentCodeStandardModel,
    DocumentSiteCodeModel,
)
from app.modules.logistics.documents.series.series_models import (
    DocumentSeriesModel,
    DocumentTalonarioModel,
    DocumentNumberModel,
    IdempotencyRecordModel,
)
from app.modules.logistics.company_profile.models import (
    OrganizationAddressModel,
    OrganizationProfileModel,
)
from app.modules.logistics.partners.models import (
    BusinessPartnerModel,
    BusinessPartnerRoleModel,
)
from app.modules.logistics.products.models import ProductModel
from app.modules.logistics.procurement.purchase_orders.infrastructure.persistence.models import (
    PurchaseOrderModel,
    PurchaseOrderRevisionModel,
    PurchaseOrderLineModel,
    PurchaseOrderSourceAllocationModel,
    PurchaseOrderSourceVarianceModel,
    PurchaseOrderTaxComponentModel,
    PurchaseOrderChargeModel,
    PurchaseOrderPaymentTermsModel,
    PurchaseOrderDeliveryTermsModel,
    PurchaseOrderDeliveryScheduleModel,
    PurchaseOrderDeliveryScheduleLineModel,
    PurchaseOrderApprovalDecisionModel,
    PurchaseOrderDispatchModel,
    PurchaseOrderDeliveryAttemptModel,
    PurchaseOrderAcknowledgementModel,
    PurchaseOrderAmendmentModel,
)
from app.modules.logistics.vehicles.infrastructure.persistence.models import (
    VehicleModel,
    VehicleVersionModel,
    VehicleMakeModel,
    VehicleModelModel,
    VehiclePlateAssignmentModel,
    VehicleCapacityProfileModel,
    VehicleDimensionsModel,
    VehicleOwnershipAssignmentModel,
    VehicleCarrierAssignmentModel,
    VehicleDocumentModel,
)
from app.modules.logistics.units.models import (
    UnitOfMeasureModel,
    MeasurementDimensionModel,
    UnitConversionRuleModel,
)
from app.modules.logistics.vehicle_verifications.infrastructure.persistence.models import (

    VehicleVerificationSourceModel,
    VehicleVerificationProviderConfigurationModel,
    VehicleVerificationModel,
    VehicleVerificationResultModel,
    VehicleVerificationFieldProvenanceModel,
    VehicleVerificationEvidenceModel,
    AssistedVehicleVerificationModel,
    VehicleVerificationConflictModel,
    VehicleVerificationRequirementModel,
    VehicleVerificationReviewTaskModel,
)
from app.modules.logistics.drivers.infrastructure.persistence.models import (
    DriverModel,
    DriverVersionModel,
    DriverIdentityDocumentModel,
    DriverLicenseModel,
    DriverLicenseCategoryModel,
    DriverLicenseCategoryAssignmentModel,
    DriverLicenseRestrictionModel,
    DriverLicenseVehicleTypeRuleModel,
    DriverCarrierAssignmentModel,
    DriverContactModel,
    DriverEmergencyContactModel,
    DriverPhotoModel,
    DriverDocumentModel,
    DriverDocumentRequirementModel,
    DriverOperationalRestrictionModel,
    DriverUserAccountLinkModel,
)
from app.modules.logistics.files.infrastructure.persistence.models import (
    FileAssetModel,
    FileVersionModel,
    FileMetadataModel,
    FileOwnershipModel,
    FileAssociationModel,
    FileAccessGrantModel,
    FileUploadSessionModel,
    FileIntegrityRecordModel,
    SignatureArtifactMetadataModel,
    EvidenceRecordModel,
    EvidenceCustodyEventModel,
    FileRetentionPolicyModel,
    FileLegalHoldModel,
    FileDeletionRequestModel,
    FileProcessingJobModel,
)
from app.modules.logistics.cost_centers.models import CostCenterModel
from app.modules.logistics.procurement.requisitions.infrastructure.persistence.models import (
    PurchaseRequisitionModel,
    PurchaseRequisitionRevisionModel,
    PurchaseRequisitionLineModel,
    PurchaseRequisitionDecisionModel,
    PurchaseRequisitionCommentModel,
    PurchaseRequisitionDuplicateCandidateModel,
)
from app.modules.logistics.procurement.evaluations.infrastructure.persistence.models import (
    SupplierEvaluationTemplateModel,
    SupplierEvaluationTemplateVersionModel,
    EvaluationCriterionDefinitionModel,
    EvaluationRubricModel,
    EvaluationRubricLevelModel,
    QuotationEvaluationModel,
    QuotationEvaluationCandidateModel,
    QuotationEvaluationRunModel,
    QuotationCriterionScoreModel,
    ManualEvaluationScoreModel,
    EvaluationScoreOverrideModel,
    QuotationLineEvaluationModel,
    QuotationCandidateEvaluationSummaryModel,
    TechnicalComplianceAssessmentModel,
    SupplierQualitySnapshotModel,
    SupplierRiskSnapshotModel,
    EvaluationExchangeRateSnapshotModel,
    EvaluationConflictOfInterestDeclarationModel,
    QuotationEvaluationDecisionModel,
    QuotationEvaluationDecisionLineModel,
    EvaluationExportJobModel,
)
from app.modules.logistics.procurement.approvals.infrastructure.persistence.models import (
    ProcurementApprovalPolicyModel,
    ProcurementApprovalPolicyVersionModel,
    ApprovalPolicyConditionModel,
    ApprovalPolicyStepDefinitionModel,
    ApprovalEscalationRuleModel,
    ProcurementApprovalRequestModel,
    ApprovalExchangeRateSnapshotModel,
    ApprovalStepInstanceModel,
    ApprovalAssignmentModel,
    ApprovalDecisionModel,
    ApprovalInformationRequestModel,
    ApprovalDelegationModel,
    ApprovalEmergencyOverrideModel,
    ApprovalAuditSealModel,
    ApprovalIntegrityEventModel,
    ApprovalNotificationJobModel,
    ApprovalMigrationRecordModel,
)
from app.modules.logistics.inbound.arrival_notices.infrastructure.persistence.models import (
    ArrivalNoticeDriverReferenceModel,
    ArrivalNoticeExpectedLineModel,
    ArrivalNoticeModel,
    ArrivalNoticeOutboxEventModel,
    ArrivalNoticePurchaseOrderReferenceModel,
    ArrivalNoticeRevisionModel,
    ArrivalNoticeTransportDocumentModel,
    ArrivalNoticeVehicleReferenceModel,
    InboundExpectedQuantityAllocationModel,
)
from app.modules.logistics.inbound.reception_calendar.infrastructure.persistence.models import (
    ReceptionAppointmentHistoryModel,
    ReceptionAppointmentHoldModel,
    ReceptionAppointmentModel,
    ReceptionAppointmentPackageJobModel,
    WarehouseReceptionBlackoutModel,
    WarehouseReceptionCalendarModel,
    WarehouseReceptionOperatingWindowModel,
)
from app.modules.logistics.inbound.gate_control.infrastructure.persistence.models import (
    WarehouseGateModel,
    GateVerificationPolicyModel,
    GateVerificationPolicyVersionModel,
    GateVerificationCheckDefinitionModel,
    GateCheckInModel,
    GateCheckInRevisionModel,
    GateVehicleInspectionModel,
    GateDriverInspectionModel,
    GatePresentedDocumentModel,
    GateSealInspectionModel,
    GatePhotoEvidenceModel,
    GateVerificationCheckResultModel,
    GateVerificationExceptionModel,
    GateEntryDecisionModel,
    GateCheckInHoldModel,
    GateCheckInTimeCorrectionModel,
    GateCheckInCorrectionRequestModel,
    GateCheckInPackageJobModel,
)
from app.modules.logistics.inbound.dock_operations.infrastructure.persistence.models import (
    WarehouseDockModel,
    WarehouseDockCapabilityModel,
    WarehouseDockOperatingWindowModel,
    WarehouseDockBlackoutModel,
    InboundDockQueueEntryModel,
    DockAssignmentPlanModel,
    InboundDockAssignmentModel,
    DockOccupancyIntervalModel,
    UnloadingOperationModel,
    UnloadingReadinessCheckDefinitionModel,
    UnloadingReadinessCheckResultModel,
    UnloadingCompletionCheckDefinitionModel,
    UnloadingCompletionCheckResultModel,
    UnloadingResponsibleAssignmentModel,
    UnloadingEquipmentAssignmentModel,
    UnloadingSealOpeningEventModel,
    UnloadingPauseModel,
    DockOperationalEventModel,
    DockOperationalTimeCorrectionModel,
    DockOperationMetricsProjectionModel,
    DockOperationExportJobModel,
)
from app.modules.logistics.inbound.receiving.infrastructure.persistence.models import (
    InboundReceiptModel,
    InboundReceiptRevisionModel,
    InboundReceiptExpectedLineModel,
    InboundReceivedLineModel,
    InboundScanSessionModel,
    InboundScanEventModel,
    InboundScanCompensationEventModel,
    UnresolvedInboundScanModel,
    InboundLotObservationModel,
    InboundSerialObservationModel,
    InboundExpirationObservationModel,
    InboundReceiptPauseModel,
    ReceivingValidationResultModel,
    ReceptionDifferenceCandidateModel,
    InboundReceiptProgressProjectionModel,
    PurchaseOrderReceiptProgressModel,
    InboundReceiptExportJobModel,
    InboundReceiptPolicyModel,
)
from app.modules.logistics.inbound.reception_differences.infrastructure.persistence.models import (
    ReceptionDifferenceCaseModel,
    ReceptionDifferenceCaseRevisionModel,
    ReceptionDifferenceItemModel,
    ReceptionDamageDetailModel,
    ReceptionDifferenceEvidenceLinkModel,
    ReceptionDifferenceResponsiblePartyModel,
    ReceptionDifferenceReviewModel,
    ReceptionDifferenceApprovalModel,
    ReceptionDifferenceAcknowledgementModel,
    ReceptionDifferenceFollowUpRecommendationModel,
    ReceptionDifferenceDocumentPackageModel,
    ReceptionDifferenceMetricsProjectionModel,
)


__all__ = [
    "EntityCodeCounter",
    "Branch",
    "LogisticsRole",
    "LogisticsRoleScopeRule",
    "LogisticsRoleAssignment",
    "LogisticsRoleConflictRule",
    "LogisticsPermission",
    "LogisticsRolePermission",
    "LogisticsPermissionScopeRule",
    "LogisticsAuditEvent",
    "StepUpChallenge",
    "StepUpProof",
    "AuditLog",
    "BehavioralBatch",
    "Client",
    "ConsentRecord",
    "ContinuousAuthEvaluation",
    "Device",
    "ExperimentalSession",
    "FacialCapture",
    "Incident",
    "InventoryItem",
    "InventoryMovement",
    "LogisticsRoute",
    "ResearchParticipant",
    "RiskEvent",
    "RouteShipment",
    "Shipment",
    "ShipmentEvent",
    "User",
    "UserSession",
    "Organization",
    "Warehouse",
    "research_participant_code_sequence",
    "shipment_tracking_sequence",
    "DocumentFamilyModel",
    "DocumentRetentionPolicyModel",
    "DocumentTypeModel",
    "DocumentTypeVersionModel",
    "DocumentCatalogVersionModel",
    "DocumentInstanceModel",
    "DocumentSnapshotModel",
    "DocumentArtifactModel",
    "DocumentReprintModel",
    "DocumentCancellationModel",
    "DocumentExportJobModel",
    "DocumentTemplateModel",
    "DocumentTemplateVersionModel",
    "DocumentTemplateAssetModel",
    "DocumentSeriesModel",
    "DocumentTalonarioModel",
    "DocumentNumberModel",
    "IdempotencyRecordModel",
    "PurchaseOrderModel",
    "PurchaseOrderRevisionModel",
    "PurchaseOrderLineModel",
    "PurchaseOrderSourceAllocationModel",
    "PurchaseOrderSourceVarianceModel",
    "PurchaseOrderTaxComponentModel",
    "PurchaseOrderChargeModel",
    "PurchaseOrderPaymentTermsModel",
    "PurchaseOrderDeliveryTermsModel",
    "PurchaseOrderDeliveryScheduleModel",
    "PurchaseOrderDeliveryScheduleLineModel",
    "PurchaseOrderApprovalDecisionModel",
    "PurchaseOrderDispatchModel",
    "PurchaseOrderDeliveryAttemptModel",
    "PurchaseOrderAcknowledgementModel",
    "PurchaseOrderAmendmentModel",
    "ProcurementApprovalPolicyModel",
    "ProcurementApprovalPolicyVersionModel",
    "ApprovalPolicyConditionModel",
    "ApprovalPolicyStepDefinitionModel",
    "ApprovalEscalationRuleModel",
    "ProcurementApprovalRequestModel",
    "ApprovalExchangeRateSnapshotModel",
    "ApprovalStepInstanceModel",
    "ApprovalAssignmentModel",
    "ApprovalDecisionModel",
    "ApprovalInformationRequestModel",
    "ApprovalDelegationModel",
    "ApprovalEmergencyOverrideModel",
    "ApprovalAuditSealModel",
    "ApprovalIntegrityEventModel",
    "ApprovalNotificationJobModel",
    "ApprovalMigrationRecordModel",
    "ArrivalNoticeModel",
    "ArrivalNoticeRevisionModel",
    "ArrivalNoticePurchaseOrderReferenceModel",
    "ArrivalNoticeExpectedLineModel",
    "InboundExpectedQuantityAllocationModel",
    "ArrivalNoticeVehicleReferenceModel",
    "ArrivalNoticeDriverReferenceModel",
    "ArrivalNoticeTransportDocumentModel",
    "ArrivalNoticeOutboxEventModel",
    "WarehouseReceptionCalendarModel",
    "WarehouseReceptionOperatingWindowModel",
    "WarehouseReceptionBlackoutModel",
    "ReceptionAppointmentHoldModel",
    "ReceptionAppointmentModel",
    "ReceptionAppointmentHistoryModel",
    "ReceptionAppointmentPackageJobModel",
    "WarehouseGateModel",
    "GateVerificationPolicyModel",
    "GateVerificationPolicyVersionModel",
    "GateVerificationCheckDefinitionModel",
    "GateCheckInModel",
    "GateCheckInRevisionModel",
    "GateVehicleInspectionModel",
    "GateDriverInspectionModel",
    "GatePresentedDocumentModel",
    "GateSealInspectionModel",
    "GatePhotoEvidenceModel",
    "GateVerificationCheckResultModel",
    "GateVerificationExceptionModel",
    "GateEntryDecisionModel",
    "GateCheckInHoldModel",
    "GateCheckInTimeCorrectionModel",
    "GateCheckInCorrectionRequestModel",
    "GateCheckInPackageJobModel",
    "WarehouseDockModel",
    "WarehouseDockCapabilityModel",
    "WarehouseDockOperatingWindowModel",
    "WarehouseDockBlackoutModel",
    "InboundDockQueueEntryModel",
    "DockAssignmentPlanModel",
    "InboundDockAssignmentModel",
    "DockOccupancyIntervalModel",
    "UnloadingOperationModel",
    "UnloadingReadinessCheckDefinitionModel",
    "UnloadingReadinessCheckResultModel",
    "UnloadingCompletionCheckDefinitionModel",
    "UnloadingCompletionCheckResultModel",
    "UnloadingResponsibleAssignmentModel",
    "UnloadingEquipmentAssignmentModel",
    "UnloadingSealOpeningEventModel",
    "UnloadingPauseModel",
    "DockOperationalEventModel",
    "DockOperationalTimeCorrectionModel",
    "DockOperationMetricsProjectionModel",
    "DockOperationExportJobModel",
    "InboundReceiptModel",
    "InboundReceiptRevisionModel",
    "InboundReceiptExpectedLineModel",
    "InboundReceivedLineModel",
    "InboundScanSessionModel",
    "InboundScanEventModel",
    "InboundScanCompensationEventModel",
    "UnresolvedInboundScanModel",
    "InboundLotObservationModel",
    "InboundSerialObservationModel",
    "InboundExpirationObservationModel",
    "InboundReceiptPauseModel",
    "ReceivingValidationResultModel",
    "ReceptionDifferenceCandidateModel",
    "InboundReceiptProgressProjectionModel",
    "PurchaseOrderReceiptProgressModel",
    "InboundReceiptExportJobModel",
    "InboundReceiptPolicyModel",
    "ReceptionDifferenceCaseModel",
    "ReceptionDifferenceCaseRevisionModel",
    "ReceptionDifferenceItemModel",
    "ReceptionDamageDetailModel",
    "ReceptionDifferenceEvidenceLinkModel",
    "ReceptionDifferenceResponsiblePartyModel",
    "ReceptionDifferenceReviewModel",
    "ReceptionDifferenceApprovalModel",
    "ReceptionDifferenceAcknowledgementModel",
    "ReceptionDifferenceFollowUpRecommendationModel",
    "ReceptionDifferenceDocumentPackageModel",
    "ReceptionDifferenceMetricsProjectionModel",
    # Phase 043: Putaway
    "PutawayPolicyModel",
    "PutawayPolicyVersionModel",
    "StorageCompatibilityRuleModel",
    "WarehouseLocationCapacityProfileModel",
    "PutawayLocationCapacityProjectionModel",
    "WarehouseLocationProximityProfileModel",
    "PutawayRecommendationRunModel",
    "PutawayLocationCandidateModel",
    "PutawayOrderModel",
    "PutawayOrderRevisionModel",
    "PutawayTaskModel",
    "PutawayTaskDestinationModel",
    "PutawayTaskAssignmentModel",
    "PutawayLocationReservationModel",
    "PutawayExecutionSessionModel",
    "PutawayScanEventModel",
    "PutawayPlacementConfirmationModel",
    "PutawayLocationOverrideModel",
    "PutawayTaskExceptionModel",
    "PutawayTaskPauseModel",
    "OperationalInventoryPlacementModel",
    "PutawayLocationPlacementProjectionModel",
    # Phase 044: Inventory ledger
    "InventoryLedgerPartitionModel",
    "InventoryPositionModel",
    "InventoryExternalBoundaryModel",
    "InventoryMovementPostingRequestModel",
    "InventoryMovementModel",
    "InventoryMovementLineModel",
    "InventoryMovementSourceReferenceModel",
    "InventoryMovementCompensationRequestModel",
    "InventoryLedgerCheckpointModel",
    "InventoryLedgerReconciliationJobModel",
    "InventoryLedgerReconciliationResultModel",
    "InventoryKardexExportJobModel",
    "InventoryLedgerOutboxEventModel",
]
