"""Domain Enums and Value Objects for Phase 027 (Vehicles Module)."""

from enum import Enum


class VehicleType(str, Enum):
    MOTORCYCLE = "MOTORCYCLE"
    CAR = "CAR"
    VAN = "VAN"
    PANEL_VAN = "PANEL_VAN"
    PICKUP = "PICKUP"
    LIGHT_TRUCK = "LIGHT_TRUCK"
    MEDIUM_TRUCK = "MEDIUM_TRUCK"
    HEAVY_TRUCK = "HEAVY_TRUCK"
    TRACTOR_TRUCK = "TRACTOR_TRUCK"
    SEMI_TRAILER = "SEMI_TRAILER"
    TRAILER = "TRAILER"
    BUS = "BUS"
    REFRIGERATED_TRUCK = "REFRIGERATED_TRUCK"
    TANKER = "TANKER"
    PLATFORM = "PLATFORM"
    CONTAINER_CARRIER = "CONTAINER_CARRIER"
    FORKLIFT = "FORKLIFT"
    OTHER = "OTHER"


class BodyType(str, Enum):
    CLOSED_BOX = "CLOSED_BOX"
    OPEN_BOX = "OPEN_BOX"
    REFRIGERATED_BOX = "REFRIGERATED_BOX"
    CURTAIN_SIDE = "CURTAIN_SIDE"
    FLATBED = "FLATBED"
    TANK = "TANK"
    DUMP = "DUMP"
    CONTAINER_CHASSIS = "CONTAINER_CHASSIS"
    PLATFORM = "PLATFORM"
    PANEL = "PANEL"
    OTHER = "OTHER"


class VehicleLifecycleStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"
    RETIRED = "RETIRED"
    ARCHIVED = "ARCHIVED"


class VehicleOperationalStatus(str, Enum):
    NOT_EVALUATED = "NOT_EVALUATED"
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    UNDER_REVIEW = "UNDER_REVIEW"
    MAINTENANCE = "MAINTENANCE"
    DOCUMENTS_EXPIRED = "DOCUMENTS_EXPIRED"
    DOCUMENTS_INCOMPLETE = "DOCUMENTS_INCOMPLETE"
    BLOCKED = "BLOCKED"
    OUT_OF_SERVICE = "OUT_OF_SERVICE"
    RETIRED = "RETIRED"


class VehicleComplianceStatus(str, Enum):
    COMPLIANT = "COMPLIANT"
    PENDING_REVIEW = "PENDING_REVIEW"
    NON_COMPLIANT = "NON_COMPLIANT"
    WARNING = "WARNING"
    EXPIRED_DOCUMENTS = "EXPIRED_DOCUMENTS"


class OwnershipType(str, Enum):
    OWNED = "OWNED"
    LEASED = "LEASED"
    RENTED = "RENTED"
    THIRD_PARTY = "THIRD_PARTY"
    SUBCONTRACTED = "SUBCONTRACTED"
    TEMPORARY = "TEMPORARY"
    OTHER = "OTHER"


class CarrierAssignmentType(str, Enum):
    OWN_FLEET = "OWN_FLEET"
    DEDICATED = "DEDICATED"
    CONTRACTED = "CONTRACTED"
    SUBCONTRACTED = "SUBCONTRACTED"
    TEMPORARY = "TEMPORARY"


class VehicleDocumentType(str, Enum):
    REGISTRATION_CARD = "REGISTRATION_CARD"
    OWNERSHIP_DOCUMENT = "OWNERSHIP_DOCUMENT"
    SOAT = "SOAT"
    VEHICLE_INSURANCE = "VEHICLE_INSURANCE"
    TECHNICAL_INSPECTION = "TECHNICAL_INSPECTION"
    TRANSPORT_AUTHORIZATION = "TRANSPORT_AUTHORIZATION"
    OPERATING_PERMIT = "OPERATING_PERMIT"
    LEASE_AGREEMENT_REFERENCE = "LEASE_AGREEMENT_REFERENCE"
    REFRIGERATION_CERTIFICATE = "REFRIGERATION_CERTIFICATE"
    HAZARDOUS_TRANSPORT_CERTIFICATE = "HAZARDOUS_TRANSPORT_CERTIFICATE"
    WEIGHT_CERTIFICATE = "WEIGHT_CERTIFICATE"
    OTHER = "OTHER"


class VerificationStatus(str, Enum):
    NOT_VERIFIED = "NOT_VERIFIED"
    METADATA_REVIEWED = "METADATA_REVIEWED"
    PENDING_EXTERNAL_VERIFICATION = "PENDING_EXTERNAL_VERIFICATION"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
