"""Value Objects & Enums for Phase 030 — Files and Evidence Centralization."""

from enum import Enum


class FileAssetType(str, Enum):
    DOCUMENT = "DOCUMENT"
    XML = "XML"
    IMAGE = "IMAGE"
    PHOTO = "PHOTO"
    SIGNATURE_IMAGE = "SIGNATURE_IMAGE"
    SIGNED_DOCUMENT = "SIGNED_DOCUMENT"
    CERTIFICATE = "CERTIFICATE"
    EVIDENCE = "EVIDENCE"
    GENERATED_DOCUMENT = "GENERATED_DOCUMENT"
    EXPORT = "EXPORT"
    OTHER = "OTHER"


class FileClassification(str, Enum):
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"
    HIGHLY_RESTRICTED = "HIGHLY_RESTRICTED"
    PUBLIC_APPROVED = "PUBLIC_APPROVED"


class FileLifecycleStatus(str, Enum):
    DRAFT = "DRAFT"
    UPLOADING = "UPLOADING"
    PROCESSING = "PROCESSING"
    AVAILABLE = "AVAILABLE"
    QUARANTINED = "QUARANTINED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"
    DELETION_PENDING = "DELETION_PENDING"
    DELETED = "DELETED"
    CORRUPTED = "CORRUPTED"


class EvidenceStatus(str, Enum):
    NOT_EVIDENCE = "NOT_EVIDENCE"
    CANDIDATE = "CANDIDATE"
    ACCEPTED = "ACCEPTED"
    SUPERSEDED = "SUPERSEDED"
    REVOKED = "REVOKED"


class FileVersionStatus(str, Enum):
    INITIATED = "INITIATED"
    UPLOADING = "UPLOADING"
    UPLOADED = "UPLOADED"
    VALIDATING = "VALIDATING"
    SCANNING = "SCANNING"
    QUARANTINED = "QUARANTINED"
    AVAILABLE = "AVAILABLE"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"
    ARCHIVED = "ARCHIVED"
    DELETED = "DELETED"
    CORRUPTED = "CORRUPTED"


class UploadSessionStatus(str, Enum):
    CREATED = "CREATED"
    AUTHORIZED = "AUTHORIZED"
    UPLOADING = "UPLOADING"
    UPLOADED = "UPLOADED"
    FINALIZING = "FINALIZING"
    SCANNING = "SCANNING"
    VALIDATING = "VALIDATING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ABORTED = "ABORTED"
    EXPIRED = "EXPIRED"


class UploadMode(str, Enum):
    DIRECT_SIGNED = "DIRECT_SIGNED"
    RESUMABLE_SIGNED = "RESUMABLE_SIGNED"
    BACKEND_STREAM = "BACKEND_STREAM"
    SYSTEM_GENERATED = "SYSTEM_GENERATED"
    MIGRATION = "MIGRATION"


class MalwareScanStatus(str, Enum):
    NOT_SCANNED = "NOT_SCANNED"
    QUEUED = "QUEUED"
    SCANNING = "SCANNING"
    CLEAN = "CLEAN"
    INFECTED = "INFECTED"
    SUSPICIOUS = "SUSPICIOUS"
    ERROR = "ERROR"
    ENGINE_UNAVAILABLE = "ENGINE_UNAVAILABLE"
    TIMEOUT = "TIMEOUT"


class ContentValidationStatus(str, Enum):
    VALID = "VALID"
    VALID_WITH_WARNINGS = "VALID_WITH_WARNINGS"
    ENCRYPTED = "ENCRYPTED"
    PASSWORD_PROTECTED = "PASSWORD_PROTECTED"
    ACTIVE_CONTENT_DETECTED = "ACTIVE_CONTENT_DETECTED"
    MALFORMED = "MALFORMED"
    REJECTED = "REJECTED"


class FileAccessScope(str, Enum):
    OWNER_ONLY = "OWNER_ONLY"
    RESOURCE_INHERITED = "RESOURCE_INHERITED"
    EXPLICIT_GRANTS = "EXPLICIT_GRANTS"
    ORGANIZATION_RESTRICTED = "ORGANIZATION_RESTRICTED"
    SYSTEM_ONLY = "SYSTEM_ONLY"


class OwnerType(str, Enum):
    ORGANIZATION = "ORGANIZATION"
    USER = "USER"
    ROLE = "ROLE"
    RESOURCE = "RESOURCE"
    SYSTEM = "SYSTEM"


class ResourceType(str, Enum):
    DOCUMENT_EMISSION = "DOCUMENT_EMISSION"
    BUSINESS_PARTNER = "BUSINESS_PARTNER"
    BUSINESS_PARTNER_DOCUMENT = "BUSINESS_PARTNER_DOCUMENT"
    VEHICLE = "VEHICLE"
    VEHICLE_DOCUMENT = "VEHICLE_DOCUMENT"
    VEHICLE_VERIFICATION = "VEHICLE_VERIFICATION"
    DRIVER = "DRIVER"
    DRIVER_PHOTO = "DRIVER_PHOTO"
    DRIVER_DOCUMENT = "DRIVER_DOCUMENT"
    ORGANIZATION = "ORGANIZATION"
    BRANCH = "BRANCH"
    WAREHOUSE = "WAREHOUSE"


class AssociationType(str, Enum):
    ATTACHMENT = "ATTACHMENT"
    EVIDENCE = "EVIDENCE"
    ORIGINAL = "ORIGINAL"
    GENERATED_OUTPUT = "GENERATED_OUTPUT"
    PHOTO = "PHOTO"
    SIGNATURE = "SIGNATURE"
    CERTIFICATE = "CERTIFICATE"
    SUPPORTING_DOCUMENT = "SUPPORTING_DOCUMENT"
    EXPORT = "EXPORT"
    OTHER = "OTHER"


class EvidenceType(str, Enum):
    DOCUMENT = "DOCUMENT"
    PHOTO = "PHOTO"
    SIGNATURE = "SIGNATURE"
    CERTIFICATE = "CERTIFICATE"
    EXTERNAL_VERIFICATION = "EXTERNAL_VERIFICATION"
    RECEIPT = "RECEIPT"
    DELIVERY = "DELIVERY"
    INCIDENT = "INCIDENT"
    INVENTORY = "INVENTORY"
    TRANSPORT = "TRANSPORT"
    OTHER = "OTHER"


class EvidenceAcceptanceStatus(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"
    REVOKED = "REVOKED"


class SignatureKind(str, Enum):
    VISUAL_SIGNATURE_IMAGE = "VISUAL_SIGNATURE_IMAGE"
    CRYPTOGRAPHIC_SIGNATURE = "CRYPTOGRAPHIC_SIGNATURE"


class SignatureVerificationStatus(str, Enum):
    NOT_VERIFIED = "NOT_VERIFIED"
    FORMAT_VALID = "FORMAT_VALID"
    CRYPTOGRAPHICALLY_VALID = "CRYPTOGRAPHICALLY_VALID"
    CRYPTOGRAPHICALLY_INVALID = "CRYPTOGRAPHICALLY_INVALID"
    CERTIFICATE_EXPIRED = "CERTIFICATE_EXPIRED"
    CERTIFICATE_REVOKED = "CERTIFICATE_REVOKED"
    INCONCLUSIVE = "INCONCLUSIVE"


class RetentionDeletionMode(str, Enum):
    NEVER_AUTOMATIC = "NEVER_AUTOMATIC"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    AUTOMATIC_AFTER_RETENTION = "AUTOMATIC_AFTER_RETENTION"
    EXTERNAL_POLICY = "EXTERNAL_POLICY"


class LegalHoldStatus(str, Enum):
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"
    EXPIRED = "EXPIRED"


class FileDeletionRequestStatus(str, Enum):
    REQUESTED = "REQUESTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SCHEDULED = "SCHEDULED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
