"""Canonical Phase 036 state and classification values."""

from enum import StrEnum


class ArrivalNoticeStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    REQUIRES_CHANGES = "REQUIRES_CHANGES"
    READY_FOR_SCHEDULING = "READY_FOR_SCHEDULING"
    SCHEDULED = "SCHEDULED"
    CONFIRMED = "CONFIRMED"
    RESCHEDULE_REQUESTED = "RESCHEDULE_REQUESTED"
    CANCELLED = "CANCELLED"
    WINDOW_ELAPSED = "WINDOW_ELAPSED"
    SUPERSEDED = "SUPERSEDED"
    ARCHIVED = "ARCHIVED"


class ArrivalNoticeRevisionStatus(StrEnum):
    EDITABLE = "EDITABLE"
    SUBMITTED = "SUBMITTED"
    FROZEN = "FROZEN"
    CONFIRMED = "CONFIRMED"
    SUPERSEDED = "SUPERSEDED"
    CANCELLED = "CANCELLED"


class SubmissionChannel(StrEnum):
    INTERNAL = "INTERNAL"
    SUPPLIER_PORTAL = "SUPPLIER_PORTAL"
    EMAIL_MANUAL_ENTRY = "EMAIL_MANUAL_ENTRY"
    PHONE_MANUAL_ENTRY = "PHONE_MANUAL_ENTRY"
    API_AUTHORIZED = "API_AUTHORIZED"
    LEGACY_IMPORT = "LEGACY_IMPORT"


class ArrivalNoticeSourceType(StrEnum):
    PURCHASE_ORDER = "PURCHASE_ORDER"
    MULTIPLE_PURCHASE_ORDERS = "MULTIPLE_PURCHASE_ORDERS"
    PURCHASE_ORDER_SCHEDULE = "PURCHASE_ORDER_SCHEDULE"
    AUTHORIZED_EXCEPTION = "AUTHORIZED_EXCEPTION"


class TransportMode(StrEnum):
    REGISTERED_CARRIER = "REGISTERED_CARRIER"
    SUPPLIER_OWN_TRANSPORT = "SUPPLIER_OWN_TRANSPORT"
    INTERNAL_TRANSPORT = "INTERNAL_TRANSPORT"
    TO_BE_CONFIRMED = "TO_BE_CONFIRMED"
    AUTHORIZED_MANUAL_EXCEPTION = "AUTHORIZED_MANUAL_EXCEPTION"


class ReferenceSourceType(StrEnum):
    VEHICLE_MASTER = "VEHICLE_MASTER"
    DRIVER_MASTER = "DRIVER_MASTER"
    SUPPLIER_DECLARED_PENDING_MATCH = "SUPPLIER_DECLARED_PENDING_MATCH"
    AUTHORIZED_MANUAL_EXCEPTION = "AUTHORIZED_MANUAL_EXCEPTION"


class TransportDocumentKind(StrEnum):
    REMISSION_GUIDE = "REMISSION_GUIDE"
    CARRIER_GUIDE = "CARRIER_GUIDE"
    SUPPLIER_DISPATCH_NOTE = "SUPPLIER_DISPATCH_NOTE"
    PACKING_LIST = "PACKING_LIST"
    BILL_OF_LADING = "BILL_OF_LADING"
    WAYBILL = "WAYBILL"
    COMMERCIAL_INVOICE_REFERENCE = "COMMERCIAL_INVOICE_REFERENCE"
    CERTIFICATE = "CERTIFICATE"
    OTHER = "OTHER"


class DocumentVerificationStatus(StrEnum):
    NOT_VERIFIED = "NOT_VERIFIED"
    FORMAT_VALID = "FORMAT_VALID"
    VERIFIED_FROM_AUTHORIZED_SOURCE = "VERIFIED_FROM_AUTHORIZED_SOURCE"
    MISMATCH = "MISMATCH"
    EXPIRED = "EXPIRED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"


class AllocationStatus(StrEnum):
    HELD = "HELD"
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"
    CANCELLED = "CANCELLED"
    CONSUMED_FUTURE = "CONSUMED_FUTURE"


class SpecialRequirement(StrEnum):
    REFRIGERATION_DECLARED = "REFRIGERATION_DECLARED"
    TEMPERATURE_CONTROL_DECLARED = "TEMPERATURE_CONTROL_DECLARED"
    FRAGILE = "FRAGILE"
    HAZARDOUS_DECLARED = "HAZARDOUS_DECLARED"
    OVERSIZED = "OVERSIZED"
    HIGH_VALUE = "HIGH_VALUE"
    CERTIFICATE_REQUIRED = "CERTIFICATE_REQUIRED"
    APPOINTMENT_DOCUMENTS_REQUIRED = "APPOINTMENT_DOCUMENTS_REQUIRED"
    SPECIAL_EQUIPMENT_REQUIRED = "SPECIAL_EQUIPMENT_REQUIRED"
    OTHER = "OTHER"
