"""Phase 043 — Putaway domain enums."""

from __future__ import annotations

from enum import StrEnum


class PolicyStatus(StrEnum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"
    ARCHIVED = "ARCHIVED"


class PolicyVersionStatus(StrEnum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"
    ARCHIVED = "ARCHIVED"


class StorageCompatibilityRuleType(StrEnum):
    PRODUCT_ALLOWED = "PRODUCT_ALLOWED"
    PRODUCT_PROHIBITED = "PRODUCT_PROHIBITED"
    CATEGORY_ALLOWED = "CATEGORY_ALLOWED"
    CATEGORY_PROHIBITED = "CATEGORY_PROHIBITED"
    TEMPERATURE_REQUIRED = "TEMPERATURE_REQUIRED"
    HAZARDOUS_DECLARED_ALLOWED = "HAZARDOUS_DECLARED_ALLOWED"
    HAZARDOUS_DECLARED_PROHIBITED = "HAZARDOUS_DECLARED_PROHIBITED"
    MAX_UNIT_WEIGHT = "MAX_UNIT_WEIGHT"
    MAX_PACKAGE_WEIGHT = "MAX_PACKAGE_WEIGHT"
    MAX_TOTAL_WEIGHT = "MAX_TOTAL_WEIGHT"
    MAX_VOLUME = "MAX_VOLUME"
    MAX_HEIGHT = "MAX_HEIGHT"
    MAX_WIDTH = "MAX_WIDTH"
    MAX_DEPTH = "MAX_DEPTH"
    HUMIDITY_RESTRICTION = "HUMIDITY_RESTRICTION"
    FOOD_SEPARATION = "FOOD_SEPARATION"
    CHEMICAL_SEPARATION = "CHEMICAL_SEPARATION"
    FRAGILE_ONLY = "FRAGILE_ONLY"
    SECURITY_LEVEL_REQUIRED = "SECURITY_LEVEL_REQUIRED"
    EXPIRATION_CONTROL_REQUIRED = "EXPIRATION_CONTROL_REQUIRED"
    LOT_CONTROL_REQUIRED = "LOT_CONTROL_REQUIRED"
    SERIAL_CONTROL_REQUIRED = "SERIAL_CONTROL_REQUIRED"
    CUSTOM_DECLARATIVE = "CUSTOM_DECLARATIVE"


class StorageCompatibilityAction(StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    REQUIRE_REVIEW = "REQUIRE_REVIEW"
    APPLY_PENALTY = "APPLY_PENALTY"


class StorageCompatibilitySeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class CapacityType(StrEnum):
    QUANTITY = "QUANTITY"
    MASS = "MASS"
    VOLUME = "VOLUME"
    PALLET_POSITION_REFERENCE = "PALLET_POSITION_REFERENCE"
    PACKAGE_POSITION_REFERENCE = "PACKAGE_POSITION_REFERENCE"
    DECLARATIVE_LIMIT = "DECLARATIVE_LIMIT"


class DataQualityStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL_BASELINE = "PARTIAL_BASELINE"
    MISSING_BASELINE = "MISSING_BASELINE"
    STALE = "STALE"
    CONFLICT = "CONFLICT"
    INTEGRITY_FAILED = "INTEGRITY_FAILED"


class MetricType(StrEnum):
    WALKING_DISTANCE_METERS = "WALKING_DISTANCE_METERS"
    TRAVEL_TIME_SECONDS = "TRAVEL_TIME_SECONDS"
    AISLE_DISTANCE_UNITS = "AISLE_DISTANCE_UNITS"
    CONFIGURED_PRIORITY_RANK = "CONFIGURED_PRIORITY_RANK"
    LOCATION_GRAPH_COST = "LOCATION_GRAPH_COST"


class MetricSourceType(StrEnum):
    MANUAL_MEASUREMENT = "MANUAL_MEASUREMENT"
    WAREHOUSE_LAYOUT_IMPORT = "WAREHOUSE_LAYOUT_IMPORT"
    APPROVED_ROUTING_ENGINE = "APPROVED_ROUTING_ENGINE"
    CONFIGURED_RANK = "CONFIGURED_RANK"


class RotationStrategy(StrEnum):
    FIFO = "FIFO"
    FEFO = "FEFO"
    RECEIPT_SEQUENCE = "RECEIPT_SEQUENCE"
    EXPIRATION_ZONE = "EXPIRATION_ZONE"
    NO_ROTATION_RULE = "NO_ROTATION_RULE"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class PutawayRecommendationRunStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    NO_CANDIDATE = "NO_CANDIDATE"
    CONFLICT = "CONFLICT"
    FAILED = "FAILED"
    SUPERSEDED = "SUPERSEDED"


class PutawayCandidateStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    SELECTED = "SELECTED"
    OVERRIDDEN = "OVERRIDDEN"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class PutawayOrderStatus(StrEnum):
    DRAFT = "DRAFT"
    PLANNING = "PLANNING"
    RECOMMENDATION_READY = "RECOMMENDATION_READY"
    READY_FOR_ISSUE = "READY_FOR_ISSUE"
    ISSUED = "ISSUED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_EXCEPTIONS = "COMPLETED_WITH_EXCEPTIONS"
    CANCELLED = "CANCELLED"
    SUPERSEDED = "SUPERSEDED"


class PutawayOrderSourceType(StrEnum):
    QUALITY_RELEASE = "QUALITY_RELEASE"
    DIRECT_RELEASE = "DIRECT_RELEASE"
    MANUAL_AUTHORIZED = "MANUAL_AUTHORIZED"
    BATCH_RELEASE = "BATCH_RELEASE"
    LEGACY_IMPORT = "LEGACY_IMPORT"


class PutawayOrderRevisionStatus(StrEnum):
    EDITABLE = "EDITABLE"
    READY = "READY"
    FROZEN = "FROZEN"
    SUPERSEDED = "SUPERSEDED"
    CANCELLED = "CANCELLED"


class PutawayTaskStatus(StrEnum):
    CREATED = "CREATED"
    RECOMMENDATION_PENDING = "RECOMMENDATION_PENDING"
    READY = "READY"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    PRODUCT_SCAN_REQUIRED = "PRODUCT_SCAN_REQUIRED"
    LOCATION_SCAN_REQUIRED = "LOCATION_SCAN_REQUIRED"
    QUANTITY_CONFIRMATION_REQUIRED = "QUANTITY_CONFIRMATION_REQUIRED"
    VALIDATING = "VALIDATING"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    COMPLETED = "COMPLETED"
    EXCEPTION = "EXCEPTION"
    REPLAN_REQUIRED = "REPLAN_REQUIRED"
    PAUSED = "PAUSED"
    CANCELLED = "CANCELLED"
    SUPERSEDED = "SUPERSEDED"


class AssignmentType(StrEnum):
    USER = "USER"
    TEAM = "TEAM"
    QUEUE = "QUEUE"


class AssignmentStatus(StrEnum):
    ASSIGNED = "ASSIGNED"
    ACCEPTED = "ACCEPTED"
    DECLINED = "DECLINED"
    EXPIRED = "EXPIRED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ReservationStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CONSUMED = "CONSUMED"
    RELEASED = "RELEASED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    SUPERSEDED = "SUPERSEDED"


class ScannerType(StrEnum):
    KEYBOARD_WEDGE = "KEYBOARD_WEDGE"
    MOBILE_CAMERA = "MOBILE_CAMERA"
    HANDHELD_TERMINAL = "HANDHELD_TERMINAL"
    APPROVED_HARDWARE_SDK = "APPROVED_HARDWARE_SDK"
    MANUAL_AUTHORIZED = "MANUAL_AUTHORIZED"


class ExecutionSessionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class ScanType(StrEnum):
    PRODUCT = "PRODUCT"
    LOCATION = "LOCATION"
    SOURCE_LOCATION_OPTIONAL = "SOURCE_LOCATION_OPTIONAL"
    PACKAGE_REFERENCE = "PACKAGE_REFERENCE"
    MANUAL_AUTHORIZED = "MANUAL_AUTHORIZED"


class ScanResolutionStatus(StrEnum):
    RECORDED = "RECORDED"
    VALID = "VALID"
    INVALID = "INVALID"
    DUPLICATE = "DUPLICATE"
    REJECTED = "REJECTED"
    COMPENSATED = "COMPENSATED"


class ScanValidationStatus(StrEnum):
    MATCH = "MATCH"
    WRONG_PRODUCT = "WRONG_PRODUCT"
    AMBIGUOUS_CODE = "AMBIGUOUS_CODE"
    UNKNOWN_CODE = "UNKNOWN_CODE"
    INACTIVE_IDENTIFIER = "INACTIVE_IDENTIFIER"
    PACKAGE_MISMATCH = "PACKAGE_MISMATCH"
    REQUIRES_MANUAL_REVIEW = "REQUIRES_MANUAL_REVIEW"
    MATCH_RECOMMENDED = "MATCH_RECOMMENDED"
    VALID_ALTERNATIVE = "VALID_ALTERNATIVE"
    LOCATION_BLOCKED = "LOCATION_BLOCKED"
    LOCATION_INCOMPATIBLE = "LOCATION_INCOMPATIBLE"
    LOCATION_CAPACITY_INSUFFICIENT = "LOCATION_CAPACITY_INSUFFICIENT"
    WRONG_WAREHOUSE = "WRONG_WAREHOUSE"
    UNKNOWN_LOCATION = "UNKNOWN_LOCATION"
    RESERVATION_EXPIRED = "RESERVATION_EXPIRED"
    REPLAN_REQUIRED = "REPLAN_REQUIRED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"


class PlacementConfirmationStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    CONFIRMED_WITH_WARNING = "CONFIRMED_WITH_WARNING"
    PARTIAL = "PARTIAL"
    REVERSED_BY_COMPENSATION = "REVERSED_BY_COMPENSATION"
    SUPERSEDED = "SUPERSEDED"


class PutawayTaskDestinationStatus(StrEnum):
    PLANNED = "PLANNED"
    RESERVED = "RESERVED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    REPLAN_REQUIRED = "REPLAN_REQUIRED"


class OverrideReasonCode(StrEnum):
    ACCESS_BLOCKED = "ACCESS_BLOCKED"
    OPERATIONAL_CONGESTION = "OPERATIONAL_CONGESTION"
    LOCATION_UNREACHABLE = "LOCATION_UNREACHABLE"
    CAPACITY_CHANGED = "CAPACITY_CHANGED"
    SUPERVISOR_DIRECTION = "SUPERVISOR_DIRECTION"
    SAFETY_REASON = "SAFETY_REASON"
    OTHER_APPROVED = "OTHER_APPROVED"


class ExceptionType(StrEnum):
    WRONG_PRODUCT = "WRONG_PRODUCT"
    UNKNOWN_PRODUCT_CODE = "UNKNOWN_PRODUCT_CODE"
    AMBIGUOUS_PRODUCT_CODE = "AMBIGUOUS_PRODUCT_CODE"
    WRONG_LOCATION = "WRONG_LOCATION"
    UNKNOWN_LOCATION = "UNKNOWN_LOCATION"
    INCOMPATIBLE_LOCATION = "INCOMPATIBLE_LOCATION"
    CAPACITY_INSUFFICIENT = "CAPACITY_INSUFFICIENT"
    RESERVATION_EXPIRED = "RESERVATION_EXPIRED"
    LOCATION_BLOCKED = "LOCATION_BLOCKED"
    LOCATION_UNREACHABLE = "LOCATION_UNREACHABLE"
    DAMAGED_DURING_PUTAWAY = "DAMAGED_DURING_PUTAWAY"
    QUANTITY_MISMATCH = "QUANTITY_MISMATCH"
    PACKAGE_MISMATCH = "PACKAGE_MISMATCH"
    SCANNER_FAILURE = "SCANNER_FAILURE"
    NETWORK_FAILURE = "NETWORK_FAILURE"
    SAFETY_ISSUE = "SAFETY_ISSUE"
    OTHER = "OTHER"


class ExceptionSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ExceptionStatus(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    REPLAN_REQUIRED = "REPLAN_REQUIRED"
    RESOLVED = "RESOLVED"
    DISMISSED_WITH_REASON = "DISMISSED_WITH_REASON"
    ESCALATED = "ESCALATED"


class PauseReason(StrEnum):
    NETWORK_FAILURE = "NETWORK_FAILURE"
    SCANNER_FAILURE = "SCANNER_FAILURE"
    LOCATION_BLOCKED = "LOCATION_BLOCKED"
    CAPACITY_REVIEW = "CAPACITY_REVIEW"
    PRODUCT_REVIEW = "PRODUCT_REVIEW"
    SAFETY = "SAFETY"
    EQUIPMENT_UNAVAILABLE = "EQUIPMENT_UNAVAILABLE"
    SUPERVISOR_REVIEW = "SUPERVISOR_REVIEW"
    BREAK = "BREAK"
    OTHER = "OTHER"


class OperationalPlacementStatus(StrEnum):
    PLACED_PENDING_MOVEMENT_LEDGER = "PLACED_PENDING_MOVEMENT_LEDGER"
    PARTIALLY_PLACED = "PARTIALLY_PLACED"
    SUPERSEDED = "SUPERSEDED"
    REVERSED_FUTURE = "REVERSED_FUTURE"
    CANCELLED = "CANCELLED"


class MissingDataPolicy(StrEnum):
    BLOCK = "BLOCK"
    ZERO_SCORE = "ZERO_SCORE"
    EXCLUDE_COMPONENT_AND_RENORMALIZE = "EXCLUDE_COMPONENT_AND_RENORMALIZE"
    REQUIRE_MANUAL_REVIEW = "REQUIRE_MANUAL_REVIEW"
