"""Canonical states for calendars, holds and appointments."""

from enum import StrEnum


class ReceptionCalendarStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    ARCHIVED = "ARCHIVED"


class ReceptionHoldStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CONSUMED = "CONSUMED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class ReceptionAppointmentStatus(StrEnum):
    PROPOSED = "PROPOSED"
    HELD = "HELD"
    PENDING_CONFIRMATION = "PENDING_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    RESCHEDULE_REQUESTED = "RESCHEDULE_REQUESTED"
    RESCHEDULED = "RESCHEDULED"
    CANCELLED = "CANCELLED"
    WINDOW_ELAPSED = "WINDOW_ELAPSED"
    SUPERSEDED = "SUPERSEDED"


class AvailabilityStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    LIMITED = "LIMITED"
    FULL = "FULL"
    BLOCKED = "BLOCKED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    CAPACITY_NOT_CONFIGURED = "CAPACITY_NOT_CONFIGURED"


class BlackoutReason(StrEnum):
    MAINTENANCE = "MAINTENANCE"
    HOLIDAY = "HOLIDAY"
    INVENTORY_COUNT = "INVENTORY_COUNT"
    CAPACITY_RESTRICTION = "CAPACITY_RESTRICTION"
    SAFETY_EVENT = "SAFETY_EVENT"
    OPERATIONAL_CLOSURE = "OPERATIONAL_CLOSURE"
    OTHER = "OTHER"
