"""Value objects and Enums for Phase 028 — Vehicle Verifications."""

from enum import Enum


class VerificationSourceType(str, Enum):
    SUNARP = "SUNARP"
    MTC = "MTC"
    SBS = "SBS"
    AUTHORIZED_PROVIDER = "AUTHORIZED_PROVIDER"
    ASSISTED_OFFICIAL_REVIEW = "ASSISTED_OFFICIAL_REVIEW"
    INTERNAL_REVIEW = "INTERNAL_REVIEW"
    DOCUMENT_REVIEW = "DOCUMENT_REVIEW"
    LEGACY_IMPORT = "LEGACY_IMPORT"
    OTHER = "OTHER"


class VerificationAutomationMode(str, Enum):
    API = "API"
    AUTHORIZED_BATCH = "AUTHORIZED_BATCH"
    MANUAL_ASSISTED = "MANUAL_ASSISTED"
    DOCUMENT_REVIEW_ONLY = "DOCUMENT_REVIEW_ONLY"
    DISABLED = "DISABLED"


class SourceAuthorizationStatus(str, Enum):
    NOT_EVALUATED = "NOT_EVALUATED"
    AUTHORIZED = "AUTHORIZED"
    CONTRACTED = "CONTRACTED"
    RESTRICTED = "RESTRICTED"
    NOT_AUTHORIZED = "NOT_AUTHORIZED"
    EXPIRED = "EXPIRED"


class SourceStatus(str, Enum):
    ACTIVE = "ACTIVE"
    DEGRADED = "DEGRADED"
    DISABLED = "DISABLED"
    FAILED = "FAILED"
    UNDER_REVIEW = "UNDER_REVIEW"


class VerificationDomain(str, Enum):
    REGISTRY_IDENTITY = "REGISTRY_IDENTITY"
    REGISTERED_OWNER = "REGISTERED_OWNER"
    VEHICLE_CHARACTERISTICS = "VEHICLE_CHARACTERISTICS"
    REGISTRATION_STATUS = "REGISTRATION_STATUS"
    LIENS_AND_ENCUMBRANCES = "LIENS_AND_ENCUMBRANCES"
    TRANSPORT_AUTHORIZATION = "TRANSPORT_AUTHORIZATION"
    CARRIER_AUTHORIZATION = "CARRIER_AUTHORIZATION"
    TECHNICAL_INSPECTION = "TECHNICAL_INSPECTION"
    SOAT = "SOAT"
    CAT = "CAT"
    VEHICLE_INSURANCE = "VEHICLE_INSURANCE"
    OPERATING_PERMIT = "OPERATING_PERMIT"
    REFRIGERATION_CERTIFICATE = "REFRIGERATION_CERTIFICATE"
    HAZARDOUS_TRANSPORT_AUTHORIZATION = "HAZARDOUS_TRANSPORT_AUTHORIZATION"
    OTHER = "OTHER"


class VerificationMethod(str, Enum):
    AUTHORIZED_API = "AUTHORIZED_API"
    AUTHORIZED_BATCH = "AUTHORIZED_BATCH"
    MANUAL_ASSISTED = "MANUAL_ASSISTED"
    DOCUMENT_METADATA_REVIEW = "DOCUMENT_METADATA_REVIEW"
    DOCUMENT_VISUAL_REVIEW = "DOCUMENT_VISUAL_REVIEW"
    PROVIDER_API = "PROVIDER_API"
    LEGACY_IMPORT = "LEGACY_IMPORT"


class VerificationStatus(str, Enum):
    DRAFT = "DRAFT"
    REQUESTED = "REQUESTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"
    REVOKED = "REVOKED"
    UNDER_REVIEW = "UNDER_REVIEW"


class VerificationResultStatus(str, Enum):
    MATCH = "MATCH"
    PARTIAL_MATCH = "PARTIAL_MATCH"
    MISMATCH = "MISMATCH"
    FOUND = "FOUND"
    NOT_FOUND = "NOT_FOUND"
    VALID = "VALID"
    INVALID = "INVALID"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    EXPIRED = "EXPIRED"
    SUSPENDED = "SUSPENDED"
    WITH_RESTRICTIONS = "WITH_RESTRICTIONS"
    INCONCLUSIVE = "INCONCLUSIVE"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNKNOWN = "UNKNOWN"


class ConfidenceLevel(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NOT_EVALUATED = "NOT_EVALUATED"


class EvidenceType(str, Enum):
    PROVIDER_RESPONSE_REFERENCE = "PROVIDER_RESPONSE_REFERENCE"
    OFFICIAL_CERTIFICATE_REFERENCE = "OFFICIAL_CERTIFICATE_REFERENCE"
    SCREENSHOT_REFERENCE = "SCREENSHOT_REFERENCE"
    PDF_REFERENCE = "PDF_REFERENCE"
    XML_REFERENCE = "XML_REFERENCE"
    MANUAL_REVIEW_NOTE = "MANUAL_REVIEW_NOTE"
    DOCUMENT_REFERENCE = "DOCUMENT_REFERENCE"
    OTHER = "OTHER"


class AssistedApprovalStatus(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class ConflictType(str, Enum):
    PLATE_MISMATCH = "PLATE_MISMATCH"
    OWNER_MISMATCH = "OWNER_MISMATCH"
    MAKE_MISMATCH = "MAKE_MISMATCH"
    MODEL_MISMATCH = "MODEL_MISMATCH"
    YEAR_MISMATCH = "YEAR_MISMATCH"
    VIN_MISMATCH = "VIN_MISMATCH"
    CHASSIS_MISMATCH = "CHASSIS_MISMATCH"
    INSURANCE_STATUS_MISMATCH = "INSURANCE_STATUS_MISMATCH"
    INSPECTION_STATUS_MISMATCH = "INSPECTION_STATUS_MISMATCH"
    TRANSPORT_AUTHORIZATION_MISMATCH = "TRANSPORT_AUTHORIZATION_MISMATCH"
    EXPIRATION_MISMATCH = "EXPIRATION_MISMATCH"
    SOURCE_CONFLICT = "SOURCE_CONFLICT"
    OTHER = "OTHER"


class ConflictStatus(str, Enum):
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    RESOLVED_KEEP_MASTER = "RESOLVED_KEEP_MASTER"
    RESOLVED_APPLY_VERIFIED = "RESOLVED_APPLY_VERIFIED"
    RESOLVED_MANUAL_VALUE = "RESOLVED_MANUAL_VALUE"
    DISMISSED = "DISMISSED"
    SUPERSEDED = "SUPERSEDED"


class ConflictSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"



class StalenessStatus(str, Enum):
    FRESH = "FRESH"
    AGING = "AGING"
    STALE = "STALE"
    CRITICAL = "CRITICAL"
    EXPIRED = "EXPIRED"
    UNKNOWN = "UNKNOWN"


class VerificationComplianceStatus(str, Enum):
    NOT_EVALUATED = "NOT_EVALUATED"
    COMPLIANT = "COMPLIANT"
    PARTIALLY_COMPLIANT = "PARTIALLY_COMPLIANT"
    NON_COMPLIANT = "NON_COMPLIANT"
    EXPIRED = "EXPIRED"
    CONFLICTED = "CONFLICTED"
    UNDER_REVIEW = "UNDER_REVIEW"
