from enum import StrEnum


class ReceiptStatus(StrEnum):
    CREATED = "CREATED"
    PREPARING = "PREPARING"
    READY = "READY"
    IN_PROGRESS = "IN_PROGRESS"
    PAUSED = "PAUSED"
    VALIDATING = "VALIDATING"
    REQUIRES_CORRECTION = "REQUIRES_CORRECTION"
    REQUIRES_DIFFERENCE_REVIEW = "REQUIRES_DIFFERENCE_REVIEW"
    PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
    FULLY_RECEIVED = "FULLY_RECEIVED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    SUPERSEDED = "SUPERSEDED"
    FAILED = "FAILED"


class RevisionStatus(StrEnum):
    EDITABLE = "EDITABLE"
    IN_PROGRESS = "IN_PROGRESS"
    VALIDATING = "VALIDATING"
    FROZEN = "FROZEN"
    SUPERSEDED = "SUPERSEDED"
    CANCELLED = "CANCELLED"


class ScanSessionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class ScanEventStatus(StrEnum):
    RECORDED = "RECORDED"
    APPLIED = "APPLIED"
    REJECTED = "REJECTED"
    DUPLICATE = "DUPLICATE"
    REVERSED_BY_COMPENSATION = "REVERSED_BY_COMPENSATION"
    SUPERSEDED = "SUPERSEDED"


class ParseStatus(StrEnum):
    PARSED = "PARSED"
    PARTIALLY_PARSED = "PARTIALLY_PARSED"
    UNSUPPORTED_SYMBOLOGY = "UNSUPPORTED_SYMBOLOGY"
    INVALID_FORMAT = "INVALID_FORMAT"
    TOO_LONG = "TOO_LONG"
    EMPTY = "EMPTY"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"


RECEIPT_TRANSITIONS = {
    ReceiptStatus.CREATED: {ReceiptStatus.PREPARING, ReceiptStatus.CANCELLED},
    ReceiptStatus.PREPARING: {ReceiptStatus.READY, ReceiptStatus.REQUIRES_CORRECTION, ReceiptStatus.CANCELLED},
    ReceiptStatus.READY: {ReceiptStatus.IN_PROGRESS, ReceiptStatus.CANCELLED},
    ReceiptStatus.IN_PROGRESS: {ReceiptStatus.PAUSED, ReceiptStatus.VALIDATING, ReceiptStatus.CANCELLED},
    ReceiptStatus.PAUSED: {ReceiptStatus.IN_PROGRESS, ReceiptStatus.CANCELLED},
    ReceiptStatus.VALIDATING: {ReceiptStatus.IN_PROGRESS, ReceiptStatus.REQUIRES_CORRECTION, ReceiptStatus.REQUIRES_DIFFERENCE_REVIEW, ReceiptStatus.PARTIALLY_RECEIVED, ReceiptStatus.FULLY_RECEIVED},
    ReceiptStatus.REQUIRES_CORRECTION: {ReceiptStatus.IN_PROGRESS, ReceiptStatus.CANCELLED},
    ReceiptStatus.REQUIRES_DIFFERENCE_REVIEW: {ReceiptStatus.COMPLETED, ReceiptStatus.SUPERSEDED, ReceiptStatus.CANCELLED},
    ReceiptStatus.PARTIALLY_RECEIVED: {ReceiptStatus.COMPLETED, ReceiptStatus.IN_PROGRESS},
    ReceiptStatus.FULLY_RECEIVED: {ReceiptStatus.COMPLETED},
}
