"""add logistics and research modules

Revision ID: cac33004e190
Revises: 20260724_0002
Create Date: 2026-07-23 21:44:59.964608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cac33004e190'
down_revision: Union[str, Sequence[str], None] = '20260724_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    if op.get_bind().dialect.name != 'sqlite':
        op.execute("CREATE SEQUENCE shipment_tracking_seq START WITH 1")
        op.execute("CREATE SEQUENCE research_participant_code_seq START WITH 1")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('document_number', sa.String(length=30), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_business_name'), 'clients', ['business_name'], unique=False)
    op.create_index(op.f('ix_clients_document_number'), 'clients', ['document_number'], unique=True)
    op.create_table('logistics_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('origin', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('driver_name', sa.String(length=150), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'planned'"), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistics_routes_route_code'), 'logistics_routes', ['route_code'], unique=True)
    op.create_index(op.f('ix_logistics_routes_scheduled_date'), 'logistics_routes', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_logistics_routes_status'), 'logistics_routes', ['status'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_stock', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('minimum_stock', sa.Numeric(precision=14, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'sku', name='uq_inventory_warehouse_sku')
    )
    op.create_index(op.f('ix_inventory_items_warehouse_id'), 'inventory_items', ['warehouse_id'], unique=False)
    op.create_table('research_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('linked_user_id', sa.UUID(), nullable=True),
    sa.Column('participant_code', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawal_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_participants_linked_user_id'), 'research_participants', ['linked_user_id'], unique=False)
    op.create_index(op.f('ix_research_participants_participant_code'), 'research_participants', ['participant_code'], unique=True)
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tracking_code', sa.String(length=30), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('origin_address', sa.String(length=255), nullable=False),
    sa.Column('destination_address', sa.String(length=255), nullable=False),
    sa.Column('origin_district', sa.String(length=100), nullable=False),
    sa.Column('destination_district', sa.String(length=100), nullable=False),
    sa.Column('package_description', sa.Text(), nullable=False),
    sa.Column('package_count', sa.Integer(), nullable=False),
    sa.Column('total_weight', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('declared_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('priority', sa.String(length=20), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'registered'"), nullable=False),
    sa.Column('assigned_route_id', sa.UUID(), nullable=True),
    sa.Column('expected_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_route_id'], ['logistics_routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.CheckConstraint('package_count > 0', name='ck_shipments_package_count_positive'),
    sa.CheckConstraint('total_weight > 0', name='ck_shipments_weight_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_assigned_route_id'), 'shipments', ['assigned_route_id'], unique=False)
    op.create_index(op.f('ix_shipments_client_id'), 'shipments', ['client_id'], unique=False)
    op.create_index(op.f('ix_shipments_created_by'), 'shipments', ['created_by'], unique=False)
    op.create_index(op.f('ix_shipments_priority'), 'shipments', ['priority'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_index(op.f('ix_shipments_tracking_code'), 'shipments', ['tracking_code'], unique=True)
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('consent_version', sa.String(length=50), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['research_participants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_participant_id'), 'consent_records', ['participant_id'], unique=False)
    op.create_table('experimental_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scenario', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'created'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('facial_capture_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('keyboard_event_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('mouse_event_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('batch_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('client_timezone', sa.String(length=80), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=False),
    sa.Column('screen_height', sa.Integer(), nullable=False),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('invalid_reason', sa.Text(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['research_participants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experimental_sessions_last_activity_at'), 'experimental_sessions', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_experimental_sessions_participant_id'), 'experimental_sessions', ['participant_id'], unique=False)
    op.create_index(op.f('ix_experimental_sessions_scenario'), 'experimental_sessions', ['scenario'], unique=False)
    op.create_index(op.f('ix_experimental_sessions_started_at'), 'experimental_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_experimental_sessions_status'), 'experimental_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_experimental_sessions_user_id'), 'experimental_sessions', ['user_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_incident_type'), 'incidents', ['incident_type'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_shipment_id'), 'incidents', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('previous_stock', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('resulting_stock', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.CheckConstraint('quantity > 0', name='ck_inventory_movement_quantity_positive'),
    sa.CheckConstraint('resulting_stock >= 0', name='ck_inventory_movement_stock_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_created_at'), 'inventory_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_movements_inventory_item_id'), 'inventory_movements', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_movement_type'), 'inventory_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_inventory_movements_shipment_id'), 'inventory_movements', ['shipment_id'], unique=False)
    op.create_table('route_shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['logistics_routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'shipment_id', name='uq_route_shipment')
    )
    op.create_index(op.f('ix_route_shipments_route_id'), 'route_shipments', ['route_id'], unique=False)
    op.create_index(op.f('ix_route_shipments_shipment_id'), 'route_shipments', ['shipment_id'], unique=False)
    op.create_table('shipment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_events_created_at'), 'shipment_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_shipment_events_new_status'), 'shipment_events', ['new_status'], unique=False)
    op.create_index(op.f('ix_shipment_events_shipment_id'), 'shipment_events', ['shipment_id'], unique=False)
    op.create_table('behavioral_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experimental_session_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('keyboard_event_count', sa.Integer(), nullable=False),
    sa.Column('mouse_event_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('processing_status', sa.String(length=30), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experimental_session_id'], ['experimental_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experimental_session_id', 'sequence_number', name='uq_behavior_session_sequence')
    )
    op.create_index(op.f('ix_behavioral_batches_batch_id'), 'behavioral_batches', ['batch_id'], unique=True)
    op.create_index(op.f('ix_behavioral_batches_experimental_session_id'), 'behavioral_batches', ['experimental_session_id'], unique=False)
    op.create_table('facial_captures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experimental_session_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visibility_state', sa.String(length=30), nullable=True),
    sa.Column('processing_status', sa.String(length=30), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experimental_session_id'], ['experimental_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experimental_session_id', 'sequence_number', name='uq_facial_capture_session_sequence')
    )
    op.create_index(op.f('ix_facial_captures_experimental_session_id'), 'facial_captures', ['experimental_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facial_captures_experimental_session_id'), table_name='facial_captures')
    op.drop_table('facial_captures')
    op.drop_index(op.f('ix_behavioral_batches_experimental_session_id'), table_name='behavioral_batches')
    op.drop_index(op.f('ix_behavioral_batches_batch_id'), table_name='behavioral_batches')
    op.drop_table('behavioral_batches')
    op.drop_index(op.f('ix_shipment_events_shipment_id'), table_name='shipment_events')
    op.drop_index(op.f('ix_shipment_events_new_status'), table_name='shipment_events')
    op.drop_index(op.f('ix_shipment_events_created_at'), table_name='shipment_events')
    op.drop_table('shipment_events')
    op.drop_index(op.f('ix_route_shipments_shipment_id'), table_name='route_shipments')
    op.drop_index(op.f('ix_route_shipments_route_id'), table_name='route_shipments')
    op.drop_table('route_shipments')
    op.drop_index(op.f('ix_inventory_movements_shipment_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_movement_type'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_inventory_item_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_created_at'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_shipment_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_type'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_experimental_sessions_user_id'), table_name='experimental_sessions')
    op.drop_index(op.f('ix_experimental_sessions_status'), table_name='experimental_sessions')
    op.drop_index(op.f('ix_experimental_sessions_started_at'), table_name='experimental_sessions')
    op.drop_index(op.f('ix_experimental_sessions_scenario'), table_name='experimental_sessions')
    op.drop_index(op.f('ix_experimental_sessions_participant_id'), table_name='experimental_sessions')
    op.drop_index(op.f('ix_experimental_sessions_last_activity_at'), table_name='experimental_sessions')
    op.drop_table('experimental_sessions')
    op.drop_index(op.f('ix_consent_records_participant_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_shipments_tracking_code'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_priority'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_created_by'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_client_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_assigned_route_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_research_participants_participant_code'), table_name='research_participants')
    op.drop_index(op.f('ix_research_participants_linked_user_id'), table_name='research_participants')
    op.drop_table('research_participants')
    op.drop_index(op.f('ix_inventory_items_warehouse_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_logistics_routes_status'), table_name='logistics_routes')
    op.drop_index(op.f('ix_logistics_routes_scheduled_date'), table_name='logistics_routes')
    op.drop_index(op.f('ix_logistics_routes_route_code'), table_name='logistics_routes')
    op.drop_table('logistics_routes')
    op.drop_index(op.f('ix_clients_document_number'), table_name='clients')
    op.drop_index(op.f('ix_clients_business_name'), table_name='clients')
    op.drop_table('clients')
    if op.get_bind().dialect.name != 'sqlite':
        op.execute("DROP SEQUENCE IF EXISTS research_participant_code_seq")
        op.execute("DROP SEQUENCE IF EXISTS shipment_tracking_seq")
    # ### end Alembic commands ###
