from enum import StrEnum


class CaseStatus(StrEnum):
    DRAFT = "DRAFT"
    UNDER_PREPARATION = "UNDER_PREPARATION"
    PENDING_EVIDENCE = "PENDING_EVIDENCE"
    PENDING_RESPONSIBILITY = "PENDING_RESPONSIBILITY"
    SUBMITTED_FOR_REVIEW = "SUBMITTED_FOR_REVIEW"
    UNDER_REVIEW = "UNDER_REVIEW"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    READY_FOR_APPROVAL = "READY_FOR_APPROVAL"
    APPROVED = "APPROVED"
    ISSUED = "ISSUED"
    ACKNOWLEDGEMENT_PENDING = "ACKNOWLEDGEMENT_PENDING"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    DISPUTED = "DISPUTED"
    FOLLOW_UP_REQUIRED = "FOLLOW_UP_REQUIRED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    SUPERSEDED = "SUPERSEDED"


CASE_TRANSITIONS = {
    CaseStatus.DRAFT: {CaseStatus.UNDER_PREPARATION, CaseStatus.CANCELLED},
    CaseStatus.UNDER_PREPARATION: {CaseStatus.PENDING_EVIDENCE, CaseStatus.PENDING_RESPONSIBILITY, CaseStatus.SUBMITTED_FOR_REVIEW, CaseStatus.CANCELLED},
    CaseStatus.PENDING_EVIDENCE: {CaseStatus.UNDER_PREPARATION, CaseStatus.SUBMITTED_FOR_REVIEW, CaseStatus.CANCELLED},
    CaseStatus.PENDING_RESPONSIBILITY: {CaseStatus.UNDER_PREPARATION, CaseStatus.SUBMITTED_FOR_REVIEW, CaseStatus.CANCELLED},
    CaseStatus.SUBMITTED_FOR_REVIEW: {CaseStatus.UNDER_REVIEW, CaseStatus.CHANGES_REQUESTED, CaseStatus.CANCELLED},
    CaseStatus.UNDER_REVIEW: {CaseStatus.CHANGES_REQUESTED, CaseStatus.READY_FOR_APPROVAL, CaseStatus.CANCELLED},
    CaseStatus.CHANGES_REQUESTED: {CaseStatus.UNDER_PREPARATION, CaseStatus.SUBMITTED_FOR_REVIEW},
    CaseStatus.READY_FOR_APPROVAL: {CaseStatus.APPROVED, CaseStatus.CHANGES_REQUESTED},
    CaseStatus.APPROVED: {CaseStatus.ISSUED},
    CaseStatus.ISSUED: {CaseStatus.ACKNOWLEDGEMENT_PENDING, CaseStatus.ACKNOWLEDGED, CaseStatus.DISPUTED, CaseStatus.FOLLOW_UP_REQUIRED, CaseStatus.CLOSED},
    CaseStatus.ACKNOWLEDGEMENT_PENDING: {CaseStatus.ACKNOWLEDGED, CaseStatus.DISPUTED, CaseStatus.FOLLOW_UP_REQUIRED},
    CaseStatus.ACKNOWLEDGED: {CaseStatus.FOLLOW_UP_REQUIRED, CaseStatus.CLOSED},
    CaseStatus.DISPUTED: {CaseStatus.FOLLOW_UP_REQUIRED, CaseStatus.CLOSED},
    CaseStatus.FOLLOW_UP_REQUIRED: {CaseStatus.CLOSED},
    CaseStatus.CLOSED: set(),
    CaseStatus.CANCELLED: set(),
    CaseStatus.SUPERSEDED: set(),
}


class CaseRevisionStatus(StrEnum):
    EDITABLE = "EDITABLE"
    SUBMITTED = "SUBMITTED"
    REVIEWED = "REVIEWED"
    APPROVED = "APPROVED"
    FROZEN = "FROZEN"
    SUPERSEDED = "SUPERSEDED"
    CANCELLED = "CANCELLED"


class ItemStatus(StrEnum):
    OPEN = "OPEN"
    EVIDENCE_PENDING = "EVIDENCE_PENDING"
    RESPONSIBILITY_PENDING = "RESPONSIBILITY_PENDING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    CONFIRMED = "CONFIRMED"
    DISMISSED_WITH_REASON = "DISMISSED_WITH_REASON"
    DISPUTED = "DISPUTED"
    FOLLOW_UP_REQUIRED = "FOLLOW_UP_REQUIRED"
    CLOSED = "CLOSED"
    SUPERSEDED = "SUPERSEDED"


class DifferenceType(StrEnum):
    SHORTAGE = "SHORTAGE"
    OVERAGE = "OVERAGE"
    QUANTITY_MISMATCH = "QUANTITY_MISMATCH"
    UNIT_MISMATCH = "UNIT_MISMATCH"
    WRONG_PRODUCT = "WRONG_PRODUCT"
    UNKNOWN_PRODUCT = "UNKNOWN_PRODUCT"
    UNEXPECTED_PRODUCT = "UNEXPECTED_PRODUCT"
    PRODUCT_DAMAGED = "PRODUCT_DAMAGED"
    PACKAGING_DAMAGED = "PACKAGING_DAMAGED"
    LABEL_UNREADABLE = "LABEL_UNREADABLE"
    CONTAMINATION_SUSPECTED = "CONTAMINATION_SUSPECTED"
    TEMPERATURE_CONCERN = "TEMPERATURE_CONCERN"
    LOT_MISSING = "LOT_MISSING"
    LOT_MISMATCH = "LOT_MISMATCH"
    SERIAL_MISSING = "SERIAL_MISSING"
    SERIAL_DUPLICATE = "SERIAL_DUPLICATE"
    SERIAL_MISMATCH = "SERIAL_MISMATCH"
    EXPIRATION_MISSING = "EXPIRATION_MISSING"
    EXPIRED_PRODUCT = "EXPIRED_PRODUCT"
    MINIMUM_SHELF_LIFE_NOT_MET = "MINIMUM_SHELF_LIFE_NOT_MET"
    DOCUMENT_MISSING = "DOCUMENT_MISSING"
    DOCUMENT_MISMATCH = "DOCUMENT_MISMATCH"
    GUIDE_MISSING = "GUIDE_MISSING"
    GUIDE_MISMATCH = "GUIDE_MISMATCH"
    CERTIFICATE_MISSING = "CERTIFICATE_MISSING"
    CERTIFICATE_INVALID_FORMAT = "CERTIFICATE_INVALID_FORMAT"
    PACKING_LIST_MISSING = "PACKING_LIST_MISSING"
    SEAL_MISSING = "SEAL_MISSING"
    SEAL_MISMATCH = "SEAL_MISMATCH"
    SEAL_BROKEN = "SEAL_BROKEN"
    SEAL_TAMPERED = "SEAL_TAMPERED"
    SEAL_DAMAGED = "SEAL_DAMAGED"
    SEAL_UNREADABLE = "SEAL_UNREADABLE"
    RECEIPT_PROCESS_ANOMALY = "RECEIPT_PROCESS_ANOMALY"
    MANUAL_ENTRY_ANOMALY = "MANUAL_ENTRY_ANOMALY"
    OTHER_APPROVED = "OTHER_APPROVED"


class DifferenceCategory(StrEnum):
    QUANTITY = "QUANTITY"
    PRODUCT = "PRODUCT"
    CONDITION = "CONDITION"
    IDENTIFICATION = "IDENTIFICATION"
    DOCUMENTATION = "DOCUMENTATION"
    SEAL = "SEAL"
    PROCESS = "PROCESS"
    SAFETY = "SAFETY"
    OTHER = "OTHER"


DIFFERENCE_TYPE_CATEGORY_MAP = {
    DifferenceType.SHORTAGE: DifferenceCategory.QUANTITY,
    DifferenceType.OVERAGE: DifferenceCategory.QUANTITY,
    DifferenceType.QUANTITY_MISMATCH: DifferenceCategory.QUANTITY,
    DifferenceType.UNIT_MISMATCH: DifferenceCategory.QUANTITY,
    DifferenceType.WRONG_PRODUCT: DifferenceCategory.PRODUCT,
    DifferenceType.UNKNOWN_PRODUCT: DifferenceCategory.PRODUCT,
    DifferenceType.UNEXPECTED_PRODUCT: DifferenceCategory.PRODUCT,
    DifferenceType.PRODUCT_DAMAGED: DifferenceCategory.CONDITION,
    DifferenceType.PACKAGING_DAMAGED: DifferenceCategory.CONDITION,
    DifferenceType.LABEL_UNREADABLE: DifferenceCategory.CONDITION,
    DifferenceType.CONTAMINATION_SUSPECTED: DifferenceCategory.SAFETY,
    DifferenceType.TEMPERATURE_CONCERN: DifferenceCategory.CONDITION,
    DifferenceType.LOT_MISSING: DifferenceCategory.IDENTIFICATION,
    DifferenceType.LOT_MISMATCH: DifferenceCategory.IDENTIFICATION,
    DifferenceType.SERIAL_MISSING: DifferenceCategory.IDENTIFICATION,
    DifferenceType.SERIAL_DUPLICATE: DifferenceCategory.IDENTIFICATION,
    DifferenceType.SERIAL_MISMATCH: DifferenceCategory.IDENTIFICATION,
    DifferenceType.EXPIRATION_MISSING: DifferenceCategory.IDENTIFICATION,
    DifferenceType.EXPIRED_PRODUCT: DifferenceCategory.CONDITION,
    DifferenceType.MINIMUM_SHELF_LIFE_NOT_MET: DifferenceCategory.CONDITION,
    DifferenceType.DOCUMENT_MISSING: DifferenceCategory.DOCUMENTATION,
    DifferenceType.DOCUMENT_MISMATCH: DifferenceCategory.DOCUMENTATION,
    DifferenceType.GUIDE_MISSING: DifferenceCategory.DOCUMENTATION,
    DifferenceType.GUIDE_MISMATCH: DifferenceCategory.DOCUMENTATION,
    DifferenceType.CERTIFICATE_MISSING: DifferenceCategory.DOCUMENTATION,
    DifferenceType.CERTIFICATE_INVALID_FORMAT: DifferenceCategory.DOCUMENTATION,
    DifferenceType.PACKING_LIST_MISSING: DifferenceCategory.DOCUMENTATION,
    DifferenceType.SEAL_MISSING: DifferenceCategory.SEAL,
    DifferenceType.SEAL_MISMATCH: DifferenceCategory.SEAL,
    DifferenceType.SEAL_BROKEN: DifferenceCategory.SEAL,
    DifferenceType.SEAL_TAMPERED: DifferenceCategory.SEAL,
    DifferenceType.SEAL_DAMAGED: DifferenceCategory.SEAL,
    DifferenceType.SEAL_UNREADABLE: DifferenceCategory.SEAL,
    DifferenceType.RECEIPT_PROCESS_ANOMALY: DifferenceCategory.PROCESS,
    DifferenceType.MANUAL_ENTRY_ANOMALY: DifferenceCategory.PROCESS,
    DifferenceType.OTHER_APPROVED: DifferenceCategory.OTHER,
}


class Severity(StrEnum):
    INFORMATIONAL = "INFORMATIONAL"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class SourceType(StrEnum):
    RECEIPT_CANDIDATES = "RECEIPT_CANDIDATES"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    GATE_CONTROL = "GATE_CONTROL"
    UNLOADING_OPERATION = "UNLOADING_OPERATION"
    DOCUMENT_REVIEW = "DOCUMENT_REVIEW"
    AUTHORIZED_IMPORT = "AUTHORIZED_IMPORT"
    LEGACY_IMPORT = "LEGACY_IMPORT"


class ResponsibilityStatus(StrEnum):
    PROPOSED = "PROPOSED"
    UNDER_REVIEW = "UNDER_REVIEW"
    ASSIGNED_INTERNAL = "ASSIGNED_INTERNAL"
    ACKNOWLEDGEMENT_PENDING = "ACKNOWLEDGEMENT_PENDING"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    DISPUTED = "DISPUTED"
    REJECTED = "REJECTED"
    UNDETERMINED = "UNDETERMINED"
    SUPERSEDED = "SUPERSEDED"


class ResponsibilityRole(StrEnum):
    PRIMARY = "PRIMARY"
    CONTRIBUTING = "CONTRIBUTING"
    NOTIFIED = "NOTIFIED"
    REVIEWER = "REVIEWER"
    UNDETERMINED = "UNDETERMINED"


class PartyType(StrEnum):
    SUPPLIER = "SUPPLIER"
    CARRIER = "CARRIER"
    INTERNAL_RECEIVING = "INTERNAL_RECEIVING"
    INTERNAL_GATE = "INTERNAL_GATE"
    INTERNAL_DOCK = "INTERNAL_DOCK"
    INTERNAL_PURCHASING = "INTERNAL_PURCHASING"
    EXTERNAL_CONTRACTOR = "EXTERNAL_CONTRACTOR"
    SHARED = "SHARED"
    UNKNOWN = "UNKNOWN"
    OTHER_APPROVED = "OTHER_APPROVED"


class ReviewType(StrEnum):
    OPERATIONAL = "OPERATIONAL"
    RECEIVING = "RECEIVING"
    WAREHOUSE_SUPERVISION = "WAREHOUSE_SUPERVISION"
    PURCHASING = "PURCHASING"
    DOCUMENTARY = "DOCUMENTARY"
    SAFETY = "SAFETY"
    QUALITY_PREPARATION = "QUALITY_PREPARATION"
    MANAGEMENT = "MANAGEMENT"


class ReviewStatus(StrEnum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class ApprovalDecision(StrEnum):
    APPROVE_FOR_ISSUE = "APPROVE_FOR_ISSUE"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    REJECT_CASE = "REJECT_CASE"
    REQUIRE_ADDITIONAL_REVIEW = "REQUIRE_ADDITIONAL_REVIEW"


class AcknowledgementType(StrEnum):
    RECEIVED_COPY = "RECEIVED_COPY"
    ACKNOWLEDGED_FACTS = "ACKNOWLEDGED_FACTS"
    ACKNOWLEDGED_RESPONSIBILITY = "ACKNOWLEDGED_RESPONSIBILITY"
    DISPUTED_FACTS = "DISPUTED_FACTS"
    DISPUTED_RESPONSIBILITY = "DISPUTED_RESPONSIBILITY"
    COMMENTED = "COMMENTED"
    NO_RESPONSE = "NO_RESPONSE"


class DamageScope(StrEnum):
    PRODUCT = "PRODUCT"
    PRIMARY_PACKAGING = "PRIMARY_PACKAGING"
    SECONDARY_PACKAGING = "SECONDARY_PACKAGING"
    TRANSPORT_PACKAGING = "TRANSPORT_PACKAGING"
    MULTIPLE = "MULTIPLE"
    UNKNOWN = "UNKNOWN"


class DamageType(StrEnum):
    CRUSHED = "CRUSHED"
    BROKEN = "BROKEN"
    TORN = "TORN"
    WET = "WET"
    OPENED = "OPENED"
    LEAKING = "LEAKING"
    CONTAMINATION_SUSPECTED = "CONTAMINATION_SUSPECTED"
    TEMPERATURE_EXCURSION_SUSPECTED = "TEMPERATURE_EXCURSION_SUSPECTED"
    SCRATCHED = "SCRATCHED"
    DEFORMED = "DEFORMED"
    MISSING_PART = "MISSING_PART"
    OTHER = "OTHER"


class EvidenceType(StrEnum):
    PRODUCT_PHOTO = "PRODUCT_PHOTO"
    PACKAGING_PHOTO = "PACKAGING_PHOTO"
    LABEL_PHOTO = "LABEL_PHOTO"
    QUANTITY_COUNT_PHOTO = "QUANTITY_COUNT_PHOTO"
    DOCUMENT_PHOTO = "DOCUMENT_PHOTO"
    GUIDE_PHOTO = "GUIDE_PHOTO"
    SEAL_PHOTO = "SEAL_PHOTO"
    TEMPERATURE_EVIDENCE = "TEMPERATURE_EVIDENCE"
    VIDEO_REFERENCE = "VIDEO_REFERENCE"
    SCAN_EVENT_REFERENCE = "SCAN_EVENT_REFERENCE"
    SYSTEM_REPORT = "SYSTEM_REPORT"
    SIGNED_ACKNOWLEDGEMENT = "SIGNED_ACKNOWLEDGEMENT"
    OTHER = "OTHER"


class FollowUpRecommendationType(StrEnum):
    QUALITY_INSPECTION_RECOMMENDED = "QUALITY_INSPECTION_RECOMMENDED"
    FUTURE_QUARANTINE_RECOMMENDED = "FUTURE_QUARANTINE_RECOMMENDED"
    SUPPLIER_REVIEW_RECOMMENDED = "SUPPLIER_REVIEW_RECOMMENDED"
    CARRIER_REVIEW_RECOMMENDED = "CARRIER_REVIEW_RECOMMENDED"
    CLAIM_RECOMMENDED = "CLAIM_RECOMMENDED"
    CORRECTIVE_ACTION_RECOMMENDED = "CORRECTIVE_ACTION_RECOMMENDED"
    DOCUMENT_RESUBMISSION_RECOMMENDED = "DOCUMENT_RESUBMISSION_RECOMMENDED"
    RETURN_REVIEW_RECOMMENDED = "RETURN_REVIEW_RECOMMENDED"
    INVENTORY_POSTING_BLOCK_RECOMMENDED = "INVENTORY_POSTING_BLOCK_RECOMMENDED"
    OTHER = "OTHER"
