from enum import StrEnum


class PlanFamily(StrEnum):
    INBOUND_RECEIVING = "INBOUND_RECEIVING"
    RECEPTION_DIFFERENCE = "RECEPTION_DIFFERENCE"
    STORAGE_REVIEW_FUTURE = "STORAGE_REVIEW_FUTURE"
    OUTBOUND_REVIEW_FUTURE = "OUTBOUND_REVIEW_FUTURE"
    GENERAL_QUALITY = "GENERAL_QUALITY"
    CUSTOM_APPROVED = "CUSTOM_APPROVED"


class PlanStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    ARCHIVED = "ARCHIVED"


class VersionStatus(StrEnum):
    DRAFT = "DRAFT"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    VALIDATED = "VALIDATED"
    SCHEDULED = "SCHEDULED"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"
    ARCHIVED = "ARCHIVED"
    SUPERSEDED = "SUPERSEDED"


class ScopeType(StrEnum):
    PRODUCT = "PRODUCT"
    PRODUCT_CATEGORY = "PRODUCT_CATEGORY"


class ResolutionSpecificity(StrEnum):
    PRODUCT_WAREHOUSE = "PRODUCT_WAREHOUSE"
    PRODUCT_BRANCH = "PRODUCT_BRANCH"
    PRODUCT_GLOBAL = "PRODUCT_GLOBAL"
    CATEGORY_WAREHOUSE = "CATEGORY_WAREHOUSE"
    CATEGORY_BRANCH = "CATEGORY_BRANCH"
    CATEGORY_GLOBAL = "CATEGORY_GLOBAL"
    PARENT_CATEGORY = "PARENT_CATEGORY"
    NO_PLAN = "NO_PLAN"


class ToleranceType(StrEnum):
    ABSOLUTE_RANGE = "ABSOLUTE_RANGE"
    TARGET_WITH_ABSOLUTE_DEVIATION = "TARGET_WITH_ABSOLUTE_DEVIATION"
    TARGET_WITH_PERCENTAGE_DEVIATION = "TARGET_WITH_PERCENTAGE_DEVIATION"
    MINIMUM_ONLY = "MINIMUM_ONLY"
    MAXIMUM_ONLY = "MAXIMUM_ONLY"
    EXACT_VALUE = "EXACT_VALUE"
    OPTION_SET = "OPTION_SET"
    BOOLEAN_REQUIRED = "BOOLEAN_REQUIRED"


class ControlType(StrEnum):
    PACKAGING_CONDITION = "PACKAGING_CONDITION"
    PACKAGING_INTEGRITY = "PACKAGING_INTEGRITY"
    LABEL_CONDITION = "LABEL_CONDITION"
    WEIGHT_MEASUREMENT = "WEIGHT_MEASUREMENT"
    TEMPERATURE_MEASUREMENT = "TEMPERATURE_MEASUREMENT"
    CERTIFICATE_PRESENCE = "CERTIFICATE_PRESENCE"
    CERTIFICATE_VALIDITY_METADATA = "CERTIFICATE_VALIDITY_METADATA"
    DOCUMENT_MATCH = "DOCUMENT_MATCH"
    SAMPLE_SELECTION = "SAMPLE_SELECTION"
    VISUAL_CONDITION = "VISUAL_CONDITION"
    EXPIRATION_REVIEW = "EXPIRATION_REVIEW"
    LOT_REVIEW = "LOT_REVIEW"
    SERIAL_REVIEW = "SERIAL_REVIEW"
    QUANTITY_REVIEW = "QUANTITY_REVIEW"
    DIMENSION_MEASUREMENT = "DIMENSION_MEASUREMENT"
    CUSTOM_DECLARATIVE = "CUSTOM_DECLARATIVE"


class SamplingType(StrEnum):
    ALL_UNITS = "ALL_UNITS"
    FIXED_COUNT = "FIXED_COUNT"
    PERCENTAGE = "PERCENTAGE"
    MINIMUM_AND_PERCENTAGE = "MINIMUM_AND_PERCENTAGE"
    ONE_PER_PACKAGE = "ONE_PER_PACKAGE"
    ONE_PER_LOT_FUTURE = "ONE_PER_LOT_FUTURE"
    DECLARATIVE_CUSTOM = "DECLARATIVE_CUSTOM"


class ContextType(StrEnum):
    INBOUND_RECEIPT_FUTURE = "INBOUND_RECEIPT_FUTURE"
    RECEPTION_DIFFERENCE_FUTURE = "RECEPTION_DIFFERENCE_FUTURE"
    MANUAL_PREVIEW = "MANUAL_PREVIEW"
    PRODUCT_CONFIGURATION_PREVIEW = "PRODUCT_CONFIGURATION_PREVIEW"


class PlanActivationTransition(StrEnum):
    DRAFT_TO_ACTIVE = "DRAFT_TO_ACTIVE"
    INACTIVE_TO_ACTIVE = "INACTIVE_TO_ACTIVE"
    ACTIVE_TO_INACTIVE = "ACTIVE_TO_INACTIVE"
    ACTIVE_TO_ARCHIVED = "ACTIVE_TO_ARCHIVED"


PLAN_STATUS_TRANSITIONS = {
    PlanStatus.DRAFT: {PlanStatus.ACTIVE},
    PlanStatus.ACTIVE: {PlanStatus.INACTIVE, PlanStatus.ARCHIVED},
    PlanStatus.INACTIVE: {PlanStatus.ACTIVE, PlanStatus.ARCHIVED},
    PlanStatus.ARCHIVED: set(),
}


VERSION_STATUS_TRANSITIONS = {
    VersionStatus.DRAFT: {VersionStatus.VALIDATION_FAILED, VersionStatus.VALIDATED},
    VersionStatus.VALIDATION_FAILED: {VersionStatus.DRAFT},
    VersionStatus.VALIDATED: {VersionStatus.SCHEDULED, VersionStatus.ACTIVE},
    VersionStatus.SCHEDULED: {VersionStatus.ACTIVE, VersionStatus.RETIRED},
    VersionStatus.ACTIVE: {VersionStatus.RETIRED, VersionStatus.SUPERSEDED},
    VersionStatus.RETIRED: {VersionStatus.ARCHIVED},
    VersionStatus.ARCHIVED: set(),
    VersionStatus.SUPERSEDED: set(),
}


CONTROL_TYPE_TOLERANCE_MAP = {
    ControlType.PACKAGING_CONDITION: [ToleranceType.OPTION_SET],
    ControlType.PACKAGING_INTEGRITY: [ToleranceType.BOOLEAN_REQUIRED],
    ControlType.LABEL_CONDITION: [ToleranceType.OPTION_SET],
    ControlType.WEIGHT_MEASUREMENT: [
        ToleranceType.ABSOLUTE_RANGE,
        ToleranceType.TARGET_WITH_ABSOLUTE_DEVIATION,
        ToleranceType.TARGET_WITH_PERCENTAGE_DEVIATION,
        ToleranceType.MINIMUM_ONLY,
        ToleranceType.MAXIMUM_ONLY,
        ToleranceType.EXACT_VALUE,
    ],
    ControlType.TEMPERATURE_MEASUREMENT: [
        ToleranceType.ABSOLUTE_RANGE,
        ToleranceType.TARGET_WITH_ABSOLUTE_DEVIATION,
        ToleranceType.MINIMUM_ONLY,
        ToleranceType.MAXIMUM_ONLY,
    ],
    ControlType.CERTIFICATE_PRESENCE: [ToleranceType.BOOLEAN_REQUIRED],
    ControlType.CERTIFICATE_VALIDITY_METADATA: [ToleranceType.OPTION_SET],
    ControlType.DOCUMENT_MATCH: [ToleranceType.BOOLEAN_REQUIRED],
    ControlType.SAMPLE_SELECTION: [ToleranceType.OPTION_SET],
    ControlType.VISUAL_CONDITION: [ToleranceType.OPTION_SET],
    ControlType.EXPIRATION_REVIEW: [
        ToleranceType.MINIMUM_ONLY,
        ToleranceType.ABSOLUTE_RANGE,
    ],
    ControlType.LOT_REVIEW: [ToleranceType.BOOLEAN_REQUIRED],
    ControlType.SERIAL_REVIEW: [ToleranceType.BOOLEAN_REQUIRED],
    ControlType.QUANTITY_REVIEW: [
        ToleranceType.ABSOLUTE_RANGE,
        ToleranceType.TARGET_WITH_ABSOLUTE_DEVIATION,
        ToleranceType.TARGET_WITH_PERCENTAGE_DEVIATION,
        ToleranceType.MINIMUM_ONLY,
        ToleranceType.MAXIMUM_ONLY,
        ToleranceType.EXACT_VALUE,
    ],
    ControlType.DIMENSION_MEASUREMENT: [
        ToleranceType.ABSOLUTE_RANGE,
        ToleranceType.TARGET_WITH_ABSOLUTE_DEVIATION,
        ToleranceType.MINIMUM_ONLY,
        ToleranceType.MAXIMUM_ONLY,
    ],
    ControlType.CUSTOM_DECLARATIVE: [
        ToleranceType.ABSOLUTE_RANGE,
        ToleranceType.TARGET_WITH_ABSOLUTE_DEVIATION,
        ToleranceType.TARGET_WITH_PERCENTAGE_DEVIATION,
        ToleranceType.MINIMUM_ONLY,
        ToleranceType.MAXIMUM_ONLY,
        ToleranceType.EXACT_VALUE,
        ToleranceType.OPTION_SET,
        ToleranceType.BOOLEAN_REQUIRED,
    ],
}
