from enum import Enum


class AvailabilityState(str, Enum):
    AVAILABLE = "AVAILABLE"
    QUARANTINE = "QUARANTINE"
    RESERVED = "RESERVED"
    BLOCKED = "BLOCKED"
    DAMAGED = "DAMAGED"
    EXPIRED = "EXPIRED"
    IN_TRANSIT = "IN_TRANSIT"
    UNKNOWN = "UNKNOWN"


class QualityState(str, Enum):
    APPROVED = "APPROVED"
    INSPECTION_PENDING = "INSPECTION_PENDING"
    QUARANTINED = "QUARANTINED"
    REJECTED = "REJECTED"


class TransitState(str, Enum):
    NOT_IN_TRANSIT = "NOT_IN_TRANSIT"
    IN_TRANSIT_INBOUND = "IN_TRANSIT_INBOUND"
    IN_TRANSIT_INTER_WAREHOUSE = "IN_TRANSIT_INTER_WAREHOUSE"
    IN_TRANSIT_OUTBOUND = "IN_TRANSIT_OUTBOUND"


class DamageState(str, Enum):
    NORMAL = "NORMAL"
    DAMAGED = "DAMAGED"
    SCRAPPED = "SCRAPPED"


class ExpirationState(str, Enum):
    FRESH = "FRESH"
    NEAR_EXPIRATION = "NEAR_EXPIRATION"
    EXPIRED = "EXPIRED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class BalanceDeltaType(str, Enum):
    INCREASE = "INCREASE"
    DECREASE = "DECREASE"
    RECONCILIATION_SET = "RECONCILIATION_SET"


class DataQualityStatus(str, Enum):
    PROJECTION_CURRENT = "PROJECTION_CURRENT"
    PROJECTION_LAGGING = "PROJECTION_LAGGING"
    PROJECTION_STALE = "PROJECTION_STALE"
    REBUILDING = "REBUILDING"


class BalanceReconciliationStatus(str, Enum):
    RECONCILED = "RECONCILED"
    MISMATCH_DETECTED = "MISMATCH_DETECTED"
    PENDING_AUDIT = "PENDING_AUDIT"
