"""Value Objects & Enums for Phase 029 — Driver Master Data."""

from enum import Enum


class DriverLifecycleStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"
    BLOCKED = "BLOCKED"
    RETIRED = "RETIRED"
    ARCHIVED = "ARCHIVED"


class DriverComplianceStatus(str, Enum):
    NOT_EVALUATED = "NOT_EVALUATED"
    COMPLIANT = "COMPLIANT"
    PARTIALLY_COMPLIANT = "PARTIALLY_COMPLIANT"
    NON_COMPLIANT = "NON_COMPLIANT"
    DOCUMENTS_EXPIRED = "DOCUMENTS_EXPIRED"
    LICENSE_EXPIRED = "LICENSE_EXPIRED"
    LICENSE_SUSPENDED = "LICENSE_SUSPENDED"
    UNDER_REVIEW = "UNDER_REVIEW"
    CONFLICTED = "CONFLICTED"


class DriverEligibilityStatus(str, Enum):
    NOT_EVALUATED = "NOT_EVALUATED"
    ELIGIBLE = "ELIGIBLE"
    INELIGIBLE = "INELIGIBLE"
    RESTRICTED = "RESTRICTED"
    LICENSE_EXPIRED = "LICENSE_EXPIRED"
    DOCUMENTS_INCOMPLETE = "DOCUMENTS_INCOMPLETE"
    CARRIER_INACTIVE = "CARRIER_INACTIVE"
    BLOCKED = "BLOCKED"
    UNDER_REVIEW = "UNDER_REVIEW"


class DriverIdentityDocumentType(str, Enum):
    DNI = "DNI"
    CE = "CE"
    PASSPORT = "PASSPORT"
    FOREIGN_ID = "FOREIGN_ID"
    OTHER = "OTHER"


class DriverIdentityVerificationStatus(str, Enum):
    NOT_VERIFIED = "NOT_VERIFIED"
    FORMAT_VALID = "FORMAT_VALID"
    METADATA_REVIEWED = "METADATA_REVIEWED"
    PENDING_EXTERNAL_VERIFICATION = "PENDING_EXTERNAL_VERIFICATION"
    VERIFIED_EXTERNAL = "VERIFIED_EXTERNAL"
    INVALID = "INVALID"
    EXPIRED = "EXPIRED"


class DriverLicenseStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"
    SUPERSEDED = "SUPERSEDED"
    ARCHIVED = "ARCHIVED"


class DriverLicenseCategoryStatus(str, Enum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"
    ARCHIVED = "ARCHIVED"


class DriverCarrierAssignmentType(str, Enum):
    INTERNAL = "INTERNAL"
    EMPLOYEE_DECLARED = "EMPLOYEE_DECLARED"
    CONTRACTED = "CONTRACTED"
    SUBCONTRACTED = "SUBCONTRACTED"
    TEMPORARY = "TEMPORARY"
    INDEPENDENT = "INDEPENDENT"
    OTHER = "OTHER"


class DriverCarrierAssignmentStatus(str, Enum):
    DRAFT = "DRAFT"
    CURRENT = "CURRENT"
    SUSPENDED = "SUSPENDED"
    SUPERSEDED = "SUPERSEDED"
    ENDED = "ENDED"


class DriverContactType(str, Enum):
    PERSONAL = "PERSONAL"
    WORK = "WORK"
    OPERATIONAL = "OPERATIONAL"
    OTHER = "OTHER"


class DriverPhotoType(str, Enum):
    PROFILE = "PROFILE"
    IDENTIFICATION_REFERENCE = "IDENTIFICATION_REFERENCE"
    OTHER = "OTHER"


class DriverPhotoStatus(str, Enum):
    ACTIVE = "ACTIVE"
    REPLACED = "REPLACED"
    REVOKED = "REVOKED"
    ARCHIVED = "ARCHIVED"


class DriverDocumentType(str, Enum):
    IDENTITY_DOCUMENT_REFERENCE = "IDENTITY_DOCUMENT_REFERENCE"
    DRIVING_LICENSE_REFERENCE = "DRIVING_LICENSE_REFERENCE"
    DRIVER_TRAINING_CERTIFICATE = "DRIVER_TRAINING_CERTIFICATE"
    SAFETY_TRAINING = "SAFETY_TRAINING"
    DEFENSIVE_DRIVING_CERTIFICATE = "DEFENSIVE_DRIVING_CERTIFICATE"
    HAZARDOUS_GOODS_TRAINING = "HAZARDOUS_GOODS_TRAINING"
    MEDICAL_FITNESS_CERTIFICATE_METADATA = "MEDICAL_FITNESS_CERTIFICATE_METADATA"
    BACKGROUND_CHECK_REFERENCE = "BACKGROUND_CHECK_REFERENCE"
    CARRIER_AUTHORIZATION = "CARRIER_AUTHORIZATION"
    OTHER = "OTHER"


class DriverRestrictionType(str, Enum):
    LICENSE_ANNOTATION = "LICENSE_ANNOTATION"
    VEHICLE_CLASS_LIMIT = "VEHICLE_CLASS_LIMIT"
    TRANSMISSION_LIMIT = "TRANSMISSION_LIMIT"
    TIME_WINDOW_LIMIT = "TIME_WINDOW_LIMIT"
    GEOGRAPHIC_LIMIT = "GEOGRAPHIC_LIMIT"
    CORRECTIVE_DEVICE_REQUIRED = "CORRECTIVE_DEVICE_REQUIRED"
    ACCOMPANIMENT_REQUIRED = "ACCOMPANIMENT_REQUIRED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    OTHER = "OTHER"


class DriverOperationalRestrictionType(str, Enum):
    MANUAL_BLOCK = "MANUAL_BLOCK"
    LICENSE_RESTRICTION = "LICENSE_RESTRICTION"
    DOCUMENT_REVIEW = "DOCUMENT_REVIEW"
    SAFETY_REVIEW = "SAFETY_REVIEW"
    CARRIER_RESTRICTION = "CARRIER_RESTRICTION"
    VEHICLE_TYPE_RESTRICTION = "VEHICLE_TYPE_RESTRICTION"
    OPERATION_TYPE_RESTRICTION = "OPERATION_TYPE_RESTRICTION"
    TEMPORARY_SUSPENSION = "TEMPORARY_SUSPENSION"
    TRAINING_REQUIRED = "TRAINING_REQUIRED"
    OTHER = "OTHER"


class DuplicateMatchLevel(str, Enum):
    DUPLICATE_CONFIRMED = "DUPLICATE_CONFIRMED"
    HIGH_PROBABILITY_DUPLICATE = "HIGH_PROBABILITY_DUPLICATE"
    POSSIBLE_DUPLICATE = "POSSIBLE_DUPLICATE"
    NOT_DUPLICATE = "NOT_DUPLICATE"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"


class DriverVehicleCompatibilityStatus(str, Enum):
    ELIGIBLE = "ELIGIBLE"
    INELIGIBLE = "INELIGIBLE"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    NOT_EVALUATED = "NOT_EVALUATED"


class UserAccountLinkStatus(str, Enum):
    NOT_LINKED = "NOT_LINKED"
    PENDING = "PENDING"
    LINKED = "LINKED"
    SUSPENDED = "SUSPENDED"
    REVOKED = "REVOKED"
