SET check_function_bodies = false;
DROP EXTENSION pg_net;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO service_role;
CREATE SEQUENCE public.research_participant_code_seq;
GRANT ALL ON SEQUENCE public.research_participant_code_seq TO anon;
GRANT ALL ON SEQUENCE public.research_participant_code_seq TO authenticated;
GRANT ALL ON SEQUENCE public.research_participant_code_seq TO service_role;
CREATE SEQUENCE public.shipment_tracking_seq;
GRANT ALL ON SEQUENCE public.shipment_tracking_seq TO anon;
GRANT ALL ON SEQUENCE public.shipment_tracking_seq TO authenticated;
GRANT ALL ON SEQUENCE public.shipment_tracking_seq TO service_role;
CREATE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;
GRANT ALL ON FUNCTION public.rls_auto_enable() TO anon;
GRANT ALL ON FUNCTION public.rls_auto_enable() TO authenticated;
GRANT ALL ON FUNCTION public.rls_auto_enable() TO service_role;
CREATE TABLE public.alembic_version (version_num character varying(32) NOT NULL);
ALTER TABLE public.alembic_version ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alembic_version ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);
GRANT ALL ON public.alembic_version TO anon;
GRANT ALL ON public.alembic_version TO authenticated;
GRANT ALL ON public.alembic_version TO service_role;
CREATE TABLE public.audit_logs (id uuid NOT NULL, user_id uuid, session_id uuid, event_type character varying(100) NOT NULL, resource_type character varying(100), resource_id character varying(255), ip_address character varying(45), user_agent text, event_metadata jsonb, created_at timestamp with time zone NOT NULL);
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);
GRANT ALL ON public.audit_logs TO anon;
GRANT ALL ON public.audit_logs TO authenticated;
GRANT ALL ON public.audit_logs TO service_role;
CREATE INDEX ix_audit_logs_user_id ON public.audit_logs (user_id);
CREATE INDEX ix_audit_logs_session_id ON public.audit_logs (session_id);
CREATE INDEX ix_audit_logs_event_type ON public.audit_logs (event_type);
CREATE INDEX ix_audit_logs_created_at ON public.audit_logs (created_at);
CREATE TABLE public.behavioral_batches (id uuid NOT NULL, experimental_session_id uuid NOT NULL, batch_id uuid NOT NULL, sequence_number integer NOT NULL, event_count integer NOT NULL, keyboard_event_count integer NOT NULL, mouse_event_count integer NOT NULL, started_at timestamp with time zone NOT NULL, ended_at timestamp with time zone NOT NULL, payload jsonb NOT NULL, checksum character varying(64) NOT NULL, processing_status character varying(30) DEFAULT 'pending'::character varying NOT NULL, received_at timestamp with time zone NOT NULL, created_at timestamp with time zone NOT NULL);
ALTER TABLE public.behavioral_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.behavioral_batches ADD CONSTRAINT behavioral_batches_pkey PRIMARY KEY (id);
ALTER TABLE public.behavioral_batches ADD CONSTRAINT uq_behavior_session_sequence UNIQUE (experimental_session_id, sequence_number);
GRANT ALL ON public.behavioral_batches TO anon;
GRANT ALL ON public.behavioral_batches TO authenticated;
GRANT ALL ON public.behavioral_batches TO service_role;
CREATE INDEX ix_behavioral_batches_experimental_session_id ON public.behavioral_batches (experimental_session_id);
CREATE UNIQUE INDEX ix_behavioral_batches_batch_id ON public.behavioral_batches (batch_id);
CREATE TABLE public.clients (id uuid NOT NULL, document_type character varying(20) NOT NULL, document_number character varying(30) NOT NULL, business_name character varying(200) NOT NULL, contact_name character varying(150), email character varying(255), phone character varying(30), address character varying(255) NOT NULL, district character varying(100) NOT NULL, province character varying(100) NOT NULL, department character varying(100) NOT NULL, is_active boolean DEFAULT true NOT NULL, is_demo boolean DEFAULT false NOT NULL, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL);
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ADD CONSTRAINT clients_pkey PRIMARY KEY (id);
GRANT ALL ON public.clients TO anon;
GRANT ALL ON public.clients TO authenticated;
GRANT ALL ON public.clients TO service_role;
CREATE UNIQUE INDEX ix_clients_document_number ON public.clients (document_number);
CREATE INDEX ix_clients_business_name ON public.clients (business_name);
CREATE TABLE public.consent_records (id uuid NOT NULL, participant_id uuid NOT NULL, consent_version character varying(50) NOT NULL, accepted boolean NOT NULL, accepted_at timestamp with time zone NOT NULL, withdrawn_at timestamp with time zone, ip_address character varying(45), created_at timestamp with time zone NOT NULL);
ALTER TABLE public.consent_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consent_records ADD CONSTRAINT consent_records_pkey PRIMARY KEY (id);
GRANT ALL ON public.consent_records TO anon;
GRANT ALL ON public.consent_records TO authenticated;
GRANT ALL ON public.consent_records TO service_role;
CREATE INDEX ix_consent_records_participant_id ON public.consent_records (participant_id);
CREATE TABLE public.devices (id uuid NOT NULL, user_id uuid NOT NULL, device_identifier character varying(255) NOT NULL, device_name character varying(150), browser character varying(100), operating_system character varying(100), device_type character varying(50), first_seen_at timestamp with time zone NOT NULL, last_seen_at timestamp with time zone NOT NULL, is_trusted boolean DEFAULT false NOT NULL, is_blocked boolean DEFAULT false NOT NULL, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL);
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.devices ADD CONSTRAINT devices_pkey PRIMARY KEY (id);
ALTER TABLE public.devices ADD CONSTRAINT uq_devices_user_identifier UNIQUE (user_id, device_identifier);
GRANT ALL ON public.devices TO anon;
GRANT ALL ON public.devices TO authenticated;
GRANT ALL ON public.devices TO service_role;
CREATE INDEX ix_devices_user_id ON public.devices (user_id);
CREATE TABLE public.experimental_sessions (id uuid NOT NULL, participant_id uuid NOT NULL, user_id uuid NOT NULL, scenario character varying(60) NOT NULL, status character varying(20) DEFAULT 'created'::character varying NOT NULL, started_at timestamp with time zone NOT NULL, ended_at timestamp with time zone, expected_duration_minutes integer NOT NULL, facial_capture_count integer DEFAULT 0 NOT NULL, keyboard_event_count integer DEFAULT 0 NOT NULL, mouse_event_count integer DEFAULT 0 NOT NULL, batch_count integer DEFAULT 0 NOT NULL, error_count integer DEFAULT 0 NOT NULL, client_timezone character varying(80), screen_width integer NOT NULL, screen_height integer NOT NULL, browser character varying(100), operating_system character varying(100), device_type character varying(50), invalid_reason text, last_activity_at timestamp with time zone NOT NULL, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL);
ALTER TABLE public.experimental_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experimental_sessions ADD CONSTRAINT experimental_sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.behavioral_batches ADD CONSTRAINT behavioral_batches_experimental_session_id_fkey FOREIGN KEY (experimental_session_id) REFERENCES public.experimental_sessions(id) ON DELETE CASCADE;
GRANT ALL ON public.experimental_sessions TO anon;
GRANT ALL ON public.experimental_sessions TO authenticated;
GRANT ALL ON public.experimental_sessions TO service_role;
CREATE INDEX ix_experimental_sessions_status ON public.experimental_sessions (status);
CREATE INDEX ix_experimental_sessions_last_activity_at ON public.experimental_sessions (last_activity_at);
CREATE INDEX ix_experimental_sessions_participant_id ON public.experimental_sessions (participant_id);
CREATE INDEX ix_experimental_sessions_scenario ON public.experimental_sessions (scenario);
CREATE INDEX ix_experimental_sessions_started_at ON public.experimental_sessions (started_at);
CREATE INDEX ix_experimental_sessions_user_id ON public.experimental_sessions (user_id);
CREATE TABLE public.facial_captures (id uuid NOT NULL, experimental_session_id uuid NOT NULL, sequence_number integer NOT NULL, storage_path character varying(500) NOT NULL, content_type character varying(50) NOT NULL, file_size integer NOT NULL, width integer NOT NULL, height integer NOT NULL, captured_at timestamp with time zone NOT NULL, received_at timestamp with time zone NOT NULL, visibility_state character varying(30), processing_status character varying(30) DEFAULT 'pending'::character varying NOT NULL, rejection_reason text, checksum character varying(64) NOT NULL, created_at timestamp with time zone NOT NULL);
ALTER TABLE public.facial_captures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facial_captures ADD CONSTRAINT facial_captures_experimental_session_id_fkey FOREIGN KEY (experimental_session_id) REFERENCES public.experimental_sessions(id) ON DELETE CASCADE;
ALTER TABLE public.facial_captures ADD CONSTRAINT facial_captures_pkey PRIMARY KEY (id);
ALTER TABLE public.facial_captures ADD CONSTRAINT uq_facial_capture_session_sequence UNIQUE (experimental_session_id, sequence_number);
GRANT ALL ON public.facial_captures TO anon;
GRANT ALL ON public.facial_captures TO authenticated;
GRANT ALL ON public.facial_captures TO service_role;
CREATE INDEX ix_facial_captures_experimental_session_id ON public.facial_captures (experimental_session_id);
CREATE TABLE public.incidents (id uuid NOT NULL, shipment_id uuid, incident_type character varying(50) NOT NULL, title character varying(200) NOT NULL, description text NOT NULL, severity character varying(20) NOT NULL, status character varying(20) DEFAULT 'open'::character varying NOT NULL, reported_by uuid NOT NULL, assigned_to uuid, resolution text, resolved_at timestamp with time zone, is_demo boolean DEFAULT false NOT NULL, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL);
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ADD CONSTRAINT incidents_pkey PRIMARY KEY (id);
GRANT ALL ON public.incidents TO anon;
GRANT ALL ON public.incidents TO authenticated;
GRANT ALL ON public.incidents TO service_role;
CREATE INDEX ix_incidents_status ON public.incidents (status);
CREATE INDEX ix_incidents_incident_type ON public.incidents (incident_type);
CREATE INDEX ix_incidents_shipment_id ON public.incidents (shipment_id);
CREATE INDEX ix_incidents_severity ON public.incidents (severity);
CREATE TABLE public.inventory_items (id uuid NOT NULL, warehouse_id uuid NOT NULL, sku character varying(60) NOT NULL, name character varying(150) NOT NULL, description text, current_stock numeric(14,3) DEFAULT 0 NOT NULL, minimum_stock numeric(14,3) DEFAULT 0 NOT NULL, unit character varying(30) NOT NULL, is_active boolean DEFAULT true NOT NULL, is_demo boolean DEFAULT false NOT NULL, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL);
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_items ADD CONSTRAINT inventory_items_pkey PRIMARY KEY (id);
ALTER TABLE public.inventory_items ADD CONSTRAINT uq_inventory_warehouse_sku UNIQUE (warehouse_id, sku);
GRANT ALL ON public.inventory_items TO anon;
GRANT ALL ON public.inventory_items TO authenticated;
GRANT ALL ON public.inventory_items TO service_role;
CREATE INDEX ix_inventory_items_warehouse_id ON public.inventory_items (warehouse_id);
CREATE TABLE public.inventory_movements (id uuid NOT NULL, inventory_item_id uuid NOT NULL, movement_type character varying(20) NOT NULL, quantity numeric(14,3) NOT NULL, previous_stock numeric(14,3) NOT NULL, resulting_stock numeric(14,3) NOT NULL, reason text NOT NULL, shipment_id uuid, created_by uuid NOT NULL, is_demo boolean DEFAULT false NOT NULL, created_at timestamp with time zone NOT NULL);
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ADD CONSTRAINT ck_inventory_movement_quantity_positive CHECK (quantity > 0::numeric);
ALTER TABLE public.inventory_movements ADD CONSTRAINT ck_inventory_movement_stock_nonnegative CHECK (resulting_stock >= 0::numeric);
ALTER TABLE public.inventory_movements ADD CONSTRAINT inventory_movements_inventory_item_id_fkey FOREIGN KEY (inventory_item_id) REFERENCES public.inventory_items(id) ON DELETE RESTRICT;
ALTER TABLE public.inventory_movements ADD CONSTRAINT inventory_movements_pkey PRIMARY KEY (id);
GRANT ALL ON public.inventory_movements TO anon;
GRANT ALL ON public.inventory_movements TO authenticated;
GRANT ALL ON public.inventory_movements TO service_role;
CREATE INDEX ix_inventory_movements_inventory_item_id ON public.inventory_movements (inventory_item_id);
CREATE INDEX ix_inventory_movements_created_at ON public.inventory_movements (created_at);
CREATE INDEX ix_inventory_movements_movement_type ON public.inventory_movements (movement_type);
CREATE INDEX ix_inventory_movements_shipment_id ON public.inventory_movements (shipment_id);
CREATE TABLE public.logistics_routes (id uuid NOT NULL, route_code character varying(50) NOT NULL, name character varying(150) NOT NULL, origin character varying(200) NOT NULL, destination character varying(200) NOT NULL, driver_name character varying(150), vehicle_plate character varying(20), scheduled_date date NOT NULL, status character varying(30) DEFAULT 'planned'::character varying NOT NULL, is_demo boolean DEFAULT false NOT NULL, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL);
ALTER TABLE public.logistics_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logistics_routes ADD CONSTRAINT logistics_routes_pkey PRIMARY KEY (id);
GRANT ALL ON public.logistics_routes TO anon;
GRANT ALL ON public.logistics_routes TO authenticated;
GRANT ALL ON public.logistics_routes TO service_role;
CREATE UNIQUE INDEX ix_logistics_routes_route_code ON public.logistics_routes (route_code);
CREATE INDEX ix_logistics_routes_status ON public.logistics_routes (status);
CREATE INDEX ix_logistics_routes_scheduled_date ON public.logistics_routes (scheduled_date);
CREATE TABLE public.research_participants (id uuid NOT NULL, linked_user_id uuid, participant_code character varying(30) NOT NULL, is_active boolean DEFAULT true NOT NULL, enrollment_date timestamp with time zone NOT NULL, withdrawal_date timestamp with time zone, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL);
ALTER TABLE public.research_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.research_participants ADD CONSTRAINT research_participants_pkey PRIMARY KEY (id);
ALTER TABLE public.consent_records ADD CONSTRAINT consent_records_participant_id_fkey FOREIGN KEY (participant_id) REFERENCES public.research_participants(id) ON DELETE RESTRICT;
ALTER TABLE public.experimental_sessions ADD CONSTRAINT experimental_sessions_participant_id_fkey FOREIGN KEY (participant_id) REFERENCES public.research_participants(id) ON DELETE RESTRICT;
GRANT ALL ON public.research_participants TO anon;
GRANT ALL ON public.research_participants TO authenticated;
GRANT ALL ON public.research_participants TO service_role;
CREATE UNIQUE INDEX ix_research_participants_participant_code ON public.research_participants (participant_code);
CREATE INDEX ix_research_participants_linked_user_id ON public.research_participants (linked_user_id);
CREATE TABLE public.route_shipments (id uuid NOT NULL, route_id uuid NOT NULL, shipment_id uuid NOT NULL, assigned_at timestamp with time zone NOT NULL, assigned_by uuid NOT NULL);
ALTER TABLE public.route_shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.route_shipments ADD CONSTRAINT route_shipments_pkey PRIMARY KEY (id);
ALTER TABLE public.route_shipments ADD CONSTRAINT route_shipments_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.logistics_routes(id) ON DELETE CASCADE;
ALTER TABLE public.route_shipments ADD CONSTRAINT uq_route_shipment UNIQUE (route_id, shipment_id);
GRANT ALL ON public.route_shipments TO anon;
GRANT ALL ON public.route_shipments TO authenticated;
GRANT ALL ON public.route_shipments TO service_role;
CREATE INDEX ix_route_shipments_shipment_id ON public.route_shipments (shipment_id);
CREATE INDEX ix_route_shipments_route_id ON public.route_shipments (route_id);
CREATE TABLE public.sessions (id uuid NOT NULL, user_id uuid NOT NULL, device_id uuid, token_hash character varying(255) NOT NULL, ip_address character varying(45), user_agent text, created_at timestamp with time zone NOT NULL, last_activity_at timestamp with time zone NOT NULL, expires_at timestamp with time zone NOT NULL, revoked_at timestamp with time zone, risk_score numeric(5,4) DEFAULT 0 NOT NULL, authentication_level character varying(50) DEFAULT 'traditional'::character varying NOT NULL, last_continuous_verification_at timestamp with time zone, created_by_login boolean DEFAULT true NOT NULL, refresh_token_hash character varying(255), previous_refresh_token_hash character varying(255), refresh_expires_at timestamp with time zone);
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ADD CONSTRAINT sessions_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(id) ON DELETE SET NULL;
ALTER TABLE public.sessions ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.audit_logs ADD CONSTRAINT audit_logs_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.sessions(id) ON DELETE SET NULL;
GRANT ALL ON public.sessions TO anon;
GRANT ALL ON public.sessions TO authenticated;
GRANT ALL ON public.sessions TO service_role;
CREATE UNIQUE INDEX ix_sessions_refresh_token_hash ON public.sessions (refresh_token_hash);
CREATE INDEX ix_sessions_expires_at ON public.sessions (expires_at);
CREATE UNIQUE INDEX ix_sessions_token_hash ON public.sessions (token_hash);
CREATE INDEX ix_sessions_user_id ON public.sessions (user_id);
CREATE INDEX ix_sessions_previous_refresh_token_hash ON public.sessions (previous_refresh_token_hash);
CREATE INDEX ix_sessions_refresh_expires_at ON public.sessions (refresh_expires_at);
CREATE TABLE public.shipment_events (id uuid NOT NULL, shipment_id uuid NOT NULL, previous_status character varying(30), new_status character varying(30) NOT NULL, description text, location character varying(200), created_by uuid NOT NULL, created_at timestamp with time zone NOT NULL);
ALTER TABLE public.shipment_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipment_events ADD CONSTRAINT shipment_events_pkey PRIMARY KEY (id);
GRANT ALL ON public.shipment_events TO anon;
GRANT ALL ON public.shipment_events TO authenticated;
GRANT ALL ON public.shipment_events TO service_role;
CREATE INDEX ix_shipment_events_created_at ON public.shipment_events (created_at);
CREATE INDEX ix_shipment_events_shipment_id ON public.shipment_events (shipment_id);
CREATE INDEX ix_shipment_events_new_status ON public.shipment_events (new_status);
CREATE TABLE public.shipments (id uuid NOT NULL, tracking_code character varying(30) NOT NULL, client_id uuid NOT NULL, origin_address character varying(255) NOT NULL, destination_address character varying(255) NOT NULL, origin_district character varying(100) NOT NULL, destination_district character varying(100) NOT NULL, package_description text NOT NULL, package_count integer NOT NULL, total_weight numeric(12,3) NOT NULL, declared_value numeric(14,2), priority character varying(20) DEFAULT 'normal'::character varying NOT NULL, status character varying(30) DEFAULT 'registered'::character varying NOT NULL, assigned_route_id uuid, expected_delivery_at timestamp with time zone, delivered_at timestamp with time zone, created_by uuid NOT NULL, is_demo boolean DEFAULT false NOT NULL, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL);
ALTER TABLE public.shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipments ADD CONSTRAINT ck_shipments_package_count_positive CHECK (package_count > 0);
ALTER TABLE public.shipments ADD CONSTRAINT ck_shipments_weight_positive CHECK (total_weight > 0::numeric);
ALTER TABLE public.shipments ADD CONSTRAINT shipments_assigned_route_id_fkey FOREIGN KEY (assigned_route_id) REFERENCES public.logistics_routes(id) ON DELETE SET NULL;
ALTER TABLE public.shipments ADD CONSTRAINT shipments_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE RESTRICT;
ALTER TABLE public.shipments ADD CONSTRAINT shipments_pkey PRIMARY KEY (id);
ALTER TABLE public.incidents ADD CONSTRAINT incidents_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id) ON DELETE SET NULL;
ALTER TABLE public.inventory_movements ADD CONSTRAINT inventory_movements_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id) ON DELETE SET NULL;
ALTER TABLE public.route_shipments ADD CONSTRAINT route_shipments_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id) ON DELETE CASCADE;
ALTER TABLE public.shipment_events ADD CONSTRAINT shipment_events_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id) ON DELETE CASCADE;
GRANT ALL ON public.shipments TO anon;
GRANT ALL ON public.shipments TO authenticated;
GRANT ALL ON public.shipments TO service_role;
CREATE INDEX ix_shipments_client_id ON public.shipments (client_id);
CREATE UNIQUE INDEX ix_shipments_tracking_code ON public.shipments (tracking_code);
CREATE INDEX ix_shipments_status ON public.shipments (status);
CREATE INDEX ix_shipments_priority ON public.shipments (priority);
CREATE INDEX ix_shipments_created_by ON public.shipments (created_by);
CREATE INDEX ix_shipments_assigned_route_id ON public.shipments (assigned_route_id);
CREATE TABLE public.users (id uuid NOT NULL, email character varying(255) NOT NULL, password_hash character varying(255) NOT NULL, full_name character varying(150) NOT NULL, role character varying(50) DEFAULT 'user'::character varying NOT NULL, is_active boolean DEFAULT true NOT NULL, is_verified boolean DEFAULT false NOT NULL, failed_login_attempts integer DEFAULT 0 NOT NULL, locked_until timestamp with time zone, last_login_at timestamp with time zone, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL);
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE public.audit_logs ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.devices ADD CONSTRAINT devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.experimental_sessions ADD CONSTRAINT experimental_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;
ALTER TABLE public.incidents ADD CONSTRAINT incidents_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.incidents ADD CONSTRAINT incidents_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES public.users(id) ON DELETE RESTRICT;
ALTER TABLE public.inventory_movements ADD CONSTRAINT inventory_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE RESTRICT;
ALTER TABLE public.research_participants ADD CONSTRAINT research_participants_linked_user_id_fkey FOREIGN KEY (linked_user_id) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.route_shipments ADD CONSTRAINT route_shipments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id) ON DELETE RESTRICT;
ALTER TABLE public.sessions ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.shipment_events ADD CONSTRAINT shipment_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE RESTRICT;
ALTER TABLE public.shipments ADD CONSTRAINT shipments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE RESTRICT;
GRANT ALL ON public.users TO anon;
GRANT ALL ON public.users TO authenticated;
GRANT ALL ON public.users TO service_role;
CREATE UNIQUE INDEX ix_users_email ON public.users (email);
CREATE TABLE public.warehouses (id uuid NOT NULL, code character varying(30) NOT NULL, name character varying(150) NOT NULL, address character varying(255) NOT NULL, district character varying(100) NOT NULL, province character varying(100) NOT NULL, department character varying(100) NOT NULL, capacity numeric(14,2), is_active boolean DEFAULT true NOT NULL, is_demo boolean DEFAULT false NOT NULL, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL);
ALTER TABLE public.warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.warehouses ADD CONSTRAINT warehouses_pkey PRIMARY KEY (id);
ALTER TABLE public.inventory_items ADD CONSTRAINT inventory_items_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE RESTRICT;
GRANT ALL ON public.warehouses TO anon;
GRANT ALL ON public.warehouses TO authenticated;
GRANT ALL ON public.warehouses TO service_role;
CREATE UNIQUE INDEX ix_warehouses_code ON public.warehouses (code);
CREATE EVENT TRIGGER ensure_rls ON ddl_command_end WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO') EXECUTE FUNCTION public.rls_auto_enable();
