"""Closed, non-executable catalogs used by Phase 038."""

from enum import StrEnum


class DockResourceType(StrEnum):
    DOCK = "DOCK"
    DOCK_DOOR = "DOCK_DOOR"
    UNLOADING_BAY = "UNLOADING_BAY"
    GROUND_LEVEL_DOOR = "GROUND_LEVEL_DOOR"
    EXTERNAL_UNLOADING_AREA = "EXTERNAL_UNLOADING_AREA"


class DockOperationDirection(StrEnum):
    INBOUND = "INBOUND"
    OUTBOUND = "OUTBOUND"
    MIXED = "MIXED"


class DockMasterStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    MAINTENANCE = "MAINTENANCE"
    BLOCKED = "BLOCKED"
    ARCHIVED = "ARCHIVED"


class DockOperationalStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    OCCUPIED = "OCCUPIED"
    UNLOADING = "UNLOADING"
    RELEASE_PENDING = "RELEASE_PENDING"
    BLOCKED = "BLOCKED"
    MAINTENANCE = "MAINTENANCE"
    INACTIVE = "INACTIVE"
    UNKNOWN = "UNKNOWN"


class QueuePriority(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    URGENT = "URGENT"
    SAFETY_CRITICAL = "SAFETY_CRITICAL"


class QueueStatus(StrEnum):
    WAITING = "WAITING"
    READY = "READY"
    ASSIGNED = "ASSIGNED"
    ON_HOLD = "ON_HOLD"
    REMOVED = "REMOVED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"


class AssignmentMode(StrEnum):
    MANUAL = "MANUAL"
    ASSISTED = "ASSISTED"
    POLICY_AUTOMATIC = "POLICY_AUTOMATIC"


class DockAssignmentStatus(StrEnum):
    ASSIGNED = "ASSIGNED"
    MOVING_TO_DOCK = "MOVING_TO_DOCK"
    AT_DOCK = "AT_DOCK"
    READY_FOR_UNLOADING = "READY_FOR_UNLOADING"
    UNLOADING_IN_PROGRESS = "UNLOADING_IN_PROGRESS"
    UNLOADING_PAUSED = "UNLOADING_PAUSED"
    UNLOADING_COMPLETED = "UNLOADING_COMPLETED"
    RELEASE_PENDING = "RELEASE_PENDING"
    DOCK_RELEASED = "DOCK_RELEASED"
    REASSIGNMENT_REQUIRED = "REASSIGNMENT_REQUIRED"
    CANCELLED = "CANCELLED"
    SUPERSEDED = "SUPERSEDED"


class CompatibilityStatus(StrEnum):
    COMPATIBLE = "COMPATIBLE"
    COMPATIBLE_WITH_WARNINGS = "COMPATIBLE_WITH_WARNINGS"
    INCOMPATIBLE = "INCOMPATIBLE"
    REQUIRES_MANUAL_REVIEW = "REQUIRES_MANUAL_REVIEW"
    INFORMATION_INCOMPLETE = "INFORMATION_INCOMPLETE"


class OccupancyStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    CORRECTED = "CORRECTED"


class UnloadingStatus(StrEnum):
    CREATED = "CREATED"
    READINESS_PENDING = "READINESS_PENDING"
    READY = "READY"
    IN_PROGRESS = "IN_PROGRESS"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    ABORTED = "ABORTED"
    CANCELLED = "CANCELLED"
    SUPERSEDED = "SUPERSEDED"


class ReadinessStatus(StrEnum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    READY = "READY"
    BLOCKED = "BLOCKED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"


class CheckResult(StrEnum):
    PASS = "PASS"
    PASS_WITH_OBSERVATION = "PASS_WITH_OBSERVATION"
    FAIL = "FAIL"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"


class UnloadingMethod(StrEnum):
    MANUAL = "MANUAL"
    FORKLIFT = "FORKLIFT"
    PALLET_JACK = "PALLET_JACK"
    CONVEYOR = "CONVEYOR"
    CRANE_DECLARED = "CRANE_DECLARED"
    MIXED = "MIXED"
    OTHER_APPROVED = "OTHER_APPROVED"


class ResponsibilityType(StrEnum):
    DOCK_PLANNER = "DOCK_PLANNER"
    DOCK_SUPERVISOR = "DOCK_SUPERVISOR"
    UNLOADING_LEAD = "UNLOADING_LEAD"
    FORKLIFT_OPERATOR = "FORKLIFT_OPERATOR"
    PALLET_JACK_OPERATOR = "PALLET_JACK_OPERATOR"
    SAFETY_OBSERVER = "SAFETY_OBSERVER"
    RECEIVING_HANDOVER = "RECEIVING_HANDOVER"
    EXTERNAL_UNLOADING_CONTRACTOR = "EXTERNAL_UNLOADING_CONTRACTOR"
    OTHER_APPROVED = "OTHER_APPROVED"


class PauseStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RESOLVED = "RESOLVED"
    CANCELLED = "CANCELLED"
    CORRECTED = "CORRECTED"


class OperationalTimeQualityStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    MISSING_REQUIRED_EVENT = "MISSING_REQUIRED_EVENT"
    EVENT_ORDER_INVALID = "EVENT_ORDER_INVALID"
    CORRECTED = "CORRECTED"
    LEGACY_IMPORTED = "LEGACY_IMPORTED"
    INTEGRITY_FAILED = "INTEGRITY_FAILED"


class CorrectionStatus(StrEnum):
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class DockOperationalEventType(StrEnum):
    QUEUED_FOR_DOCK = "QUEUED_FOR_DOCK"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"
    ASSIGNMENT_PLANNED = "ASSIGNMENT_PLANNED"
    DOCK_ASSIGNED = "DOCK_ASSIGNED"
    MOVEMENT_TO_DOCK_STARTED = "MOVEMENT_TO_DOCK_STARTED"
    ARRIVED_AT_DOCK = "ARRIVED_AT_DOCK"
    READINESS_STARTED = "READINESS_STARTED"
    READINESS_COMPLETED = "READINESS_COMPLETED"
    RESPONSIBLE_ASSIGNED = "RESPONSIBLE_ASSIGNED"
    EQUIPMENT_ASSIGNED = "EQUIPMENT_ASSIGNED"
    EQUIPMENT_RELEASED = "EQUIPMENT_RELEASED"
    SEAL_OPENED = "SEAL_OPENED"
    UNLOADING_STARTED = "UNLOADING_STARTED"
    UNLOADING_CANCELLED = "UNLOADING_CANCELLED"
    UNLOADING_PAUSED = "UNLOADING_PAUSED"
    UNLOADING_PAUSE_CANCELLED = "UNLOADING_PAUSE_CANCELLED"
    UNLOADING_RESUMED = "UNLOADING_RESUMED"
    UNLOADING_ABORTED = "UNLOADING_ABORTED"
    UNLOADING_COMPLETED = "UNLOADING_COMPLETED"
    RELEASE_PENDING = "RELEASE_PENDING"
    DOCK_RELEASED = "DOCK_RELEASED"
    DOCK_REASSIGNED = "DOCK_REASSIGNED"
    TIME_CORRECTION_REQUESTED = "TIME_CORRECTION_REQUESTED"
    TIME_CORRECTION_APPROVED = "TIME_CORRECTION_APPROVED"
    INTEGRITY_FAILED = "INTEGRITY_FAILED"


ACTIVE_QUEUE_STATUSES = {
    QueueStatus.WAITING.value,
    QueueStatus.READY.value,
    QueueStatus.ASSIGNED.value,
    QueueStatus.ON_HOLD.value,
}

ACTIVE_ASSIGNMENT_STATUSES = {
    DockAssignmentStatus.ASSIGNED.value,
    DockAssignmentStatus.MOVING_TO_DOCK.value,
    DockAssignmentStatus.AT_DOCK.value,
    DockAssignmentStatus.READY_FOR_UNLOADING.value,
    DockAssignmentStatus.UNLOADING_IN_PROGRESS.value,
    DockAssignmentStatus.UNLOADING_PAUSED.value,
    DockAssignmentStatus.UNLOADING_COMPLETED.value,
    DockAssignmentStatus.RELEASE_PENDING.value,
    DockAssignmentStatus.REASSIGNMENT_REQUIRED.value,
}

ACTIVE_UNLOADING_STATUSES = {
    UnloadingStatus.CREATED.value,
    UnloadingStatus.READINESS_PENDING.value,
    UnloadingStatus.READY.value,
    UnloadingStatus.IN_PROGRESS.value,
    UnloadingStatus.PAUSED.value,
}

GATE_AUTHORIZED_STATUSES = {
    "ENTRY_AUTHORIZED",
    "ENTRY_AUTHORIZED_WITH_OBSERVATIONS",
}

GATE_AUTHORIZED_DECISIONS = {
    "AUTHORIZE_ENTRY",
    "AUTHORIZE_WITH_OBSERVATIONS",
}
