from enum import StrEnum


class Role(StrEnum):
    ADMIN = "admin"
    SUPERVISOR = "supervisor"
    DISPATCHER = "dispatcher"
    WAREHOUSE_OPERATOR = "warehouse_operator"


LOGISTICS_READ_ROLES = tuple(Role)
CLIENT_WRITE_ROLES = (Role.ADMIN,)
SHIPMENT_WRITE_ROLES = (Role.ADMIN, Role.DISPATCHER)
SHIPMENT_STATUS_ROLES = (Role.ADMIN, Role.SUPERVISOR, Role.DISPATCHER)
WAREHOUSE_WRITE_ROLES = (Role.ADMIN,)
INVENTORY_WRITE_ROLES = (Role.ADMIN, Role.WAREHOUSE_OPERATOR)
ROUTE_WRITE_ROLES = (Role.ADMIN, Role.SUPERVISOR, Role.DISPATCHER)
INCIDENT_WRITE_ROLES = tuple(Role)
REPORT_ROLES = (Role.ADMIN, Role.SUPERVISOR)
RESEARCH_ADMIN_ROLES = (Role.ADMIN, Role.SUPERVISOR)
